import React, { useEffect, useMemo, useState } from "react";

const uid = () => Math.random().toString(36).slice(2, 10);
const STORAGE_KEY = "ki-kernel-scenarios-v6";

const menu = {
  evidence: ["niedrig", "mittel", "hoch"],
  uncertainty: ["niedrig", "mittel", "hoch"],
  sensitivity: ["unkritisch", "intern", "vertraulich", "personenbezogen vermeiden"],
  sourceStatus: ["explizit", "abgeleitet", "Hypothese"],
  role: ["Operative Praxis", "Mittlere Führung", "Geschäftsführung", "Projektleitung", "Governance", "Datenschutz", "MAV / Interessenvertretung", "QM / Prozesssteuerung", "Pädagogik", "Verwaltung", "Finanzierung", "Lerngruppe", "Stakeholder", "Sonstige Rolle"],
  stance: ["zustimmend", "experimentierfreudig", "offen, aber überlastet", "pragmatisch", "vermittelnd", "strukturierend", "prüfend", "prüfend und begrenzend", "schutzorientiert", "vorsichtig-kritisch", "skeptisch", "distanziert", "unsicher", "unklar"],
  conflictStyle: ["vermeidend", "abwartend", "kritisch nachfragend", "werteorientiert", "regelbasiert", "interessenklärend", "argumentativ", "konfrontativ", "ausgleichend", "moderierend", "lösungsorientiert", "steuernd", "unklar"],
  informalRole: ["Meinungsführer*in", "Brückenrolle", "Stoppsignal", "Treiber*in", "Realitätscheck", "Prozessanker", "Frühwarnrolle", "Seismograf für Klima", "Veto-Risiko", "formale Entscheidung", "informelle Macht", "keine besondere informelle Rolle"],
  resourceType: ["sozial", "kognitiv", "emotional", "operativ", "materiell", "governance", "kommunikativ", "lernbezogen"],
  direction: ["high_good", "low_good"],
  trend: ["steigend", "stabil", "fallend", "unklar"],
  timing: ["vorab", "Einstieg", "früh", "Mitte", "Entscheidung", "Abschluss", "nachgelagert", "regelmäßig", "offen"],
  effort: ["niedrig", "mittel", "hoch"],
  documentType: ["Konzept", "Projektantrag", "Workshopplan", "Richtlinie", "Protokoll", "Strategiepapier", "Schulungskonzept", "Sonstiges"],
  analysisMode: ["vorsichtig", "beratend", "pre-mortem"]
};

function explain(kind, value) {
  const v = Math.max(1, Math.min(5, Number(value || 3))) - 1;
  const map = {
    influence: ["Sehr geringer Einfluss: wirkt kaum auf Entscheidung oder Gruppendynamik.", "Geringer Einfluss: wird gehört, prägt aber das System nur begrenzt.", "Mittlerer Einfluss: kann Stimmungen oder Entscheidungen mitprägen.", "Hoher Einfluss: prägt Akzeptanz, Tempo oder Widerstand deutlich.", "Sehr hoher Einfluss: Schlüsselrolle; ohne diese Rolle kippt das Szenario leicht."],
    affectedness: ["Sehr geringe Betroffenheit: nur randständig berührt.", "Geringe Betroffenheit: Auswirkungen sind vorhanden, aber begrenzt.", "Mittlere Betroffenheit: spürbare Veränderung im Arbeits- oder Lernalltag.", "Hohe Betroffenheit: Veränderung betrifft Rolle, Verantwortung oder Routinen stark.", "Sehr hohe Betroffenheit: zentrale Rolle; Veränderung verändert Selbstverständnis oder Arbeitsweise."],
    trust: ["Sehr geringes Vertrauen: starke Schutz- oder Abwehrlogik wahrscheinlich.", "Geringes Vertrauen: Kommunikation muss zuerst Sicherheit erzeugen.", "Mittleres Vertrauen: Zustimmung hängt stark von Transparenz und Beteiligung ab.", "Hohes Vertrauen: Rolle kann konstruktiv mitarbeiten, wenn Grenzen klar sind.", "Sehr hohes Vertrauen: Rolle kann als Stabilisierung oder Multiplikation wirken."],
    aiLiteracy: ["Sehr geringe KI-Kompetenz: Grundlagen und Grenzen müssen zuerst geklärt werden.", "Geringe KI-Kompetenz: einfache Beispiele und sichere Anleitung nötig.", "Mittlere KI-Kompetenz: Anwendung möglich, aber Risiko- und Qualitätsfragen brauchen Begleitung.", "Hohe KI-Kompetenz: kann Use Cases entwickeln und andere unterstützen.", "Sehr hohe KI-Kompetenz: mögliche Multiplikator- oder Pilotrolle."],
    riskSense: ["Sehr geringes Risikoempfinden: Gefahr von Sorglosigkeit oder Shadow-Use.", "Geringes Risikoempfinden: Risiken müssen aktiv sichtbar gemacht werden.", "Mittleres Risikoempfinden: abwägende Haltung möglich.", "Hohes Risikoempfinden: Schutz-, Datenschutz- oder Qualitätsfragen dominieren.", "Sehr hohes Risikoempfinden: kann wertvolle Frühwarnrolle oder Blockadepunkt sein."],
    changeEnergy: ["Sehr geringe Veränderungsenergie: passive oder blockierende Dynamik möglich.", "Geringe Veränderungsenergie: Beteiligung braucht Entlastung und Sinn.", "Mittlere Veränderungsenergie: Mitgehen möglich, wenn Aufwand und Nutzen plausibel sind.", "Hohe Veränderungsenergie: Rolle kann Umsetzung aktiv unterstützen.", "Sehr hohe Veränderungsenergie: mögliche Treiber- oder Pilotrolle."],
    current: ["Sehr schwach ausgeprägt: akuter Stabilisierungsbedarf.", "Schwach ausgeprägt: Ressource ist fragil.", "Mittel ausgeprägt: tragfähig, aber beobachtungsbedürftig.", "Gut ausgeprägt: Ressource kann genutzt werden.", "Sehr stark ausgeprägt: Ressource ist ein Hebel im Szenario."],
    target: ["Minimalziel: nur basale Stabilisierung nötig.", "Niedriges Ziel: begrenzte Verbesserung reicht.", "Mittleres Ziel: solide Arbeitsfähigkeit wird angestrebt.", "Hohes Ziel: Ressource soll aktiv tragend werden.", "Sehr hohes Ziel: Ressource wird zum zentralen Erfolgsfaktor."],
    speed: ["Sehr langsam: lange Klärung vor Bewegung.", "Eher langsam: Beteiligung und Sorgfalt bremsen, erhöhen aber Anschlussfähigkeit.", "Mittleres Tempo: Klärung und Umsetzung halten sich die Waage.", "Eher schnell: rascher Start mit Kommunikationsbedarf.", "Sehr schnell: hoher Umsetzungsschub durch klare Entscheidung."],
    acceptance: ["Sehr geringe Akzeptanz: Vorgehen wirkt fremd oder belastend.", "Geringe Akzeptanz: deutliche Beteiligungs- und Vertrauensrisiken.", "Mittlere Akzeptanz: Zustimmung hängt stark von Kommunikation ab.", "Hohe Akzeptanz: Vorgehen ist anschlussfähig, wenn Grenzen klar bleiben.", "Sehr hohe Akzeptanz: passt gut zu Bedarf und Belastungslage."],
    control: ["Sehr geringe Kontrolle: Governance kaum steuerbar.", "Geringe Kontrolle: relevante Lücken und Nachsteuerungsbedarf.", "Mittlere Kontrolle: Grundregeln möglich, aber nicht vollständig abgesichert.", "Hohe Kontrolle: Zuständigkeiten und Datenregeln gut steuerbar.", "Sehr hohe Kontrolle: Governance und Qualitätssicherung klar angelegt."],
    innovation: ["Sehr gering: Lernen und Erprobung stark begrenzt.", "Gering: wenige neue Praxisimpulse.", "Mittel: Raum für Lernen, aber keine breite Erprobung.", "Hoch: praxisnahe Experimente wahrscheinlich.", "Sehr hoch: viele Use Cases und organisationales Lernen."],
    risk: ["Sehr gering: wenige erkennbare Nebenwirkungen.", "Gering: wichtigste Risiken wirken beherrschbar.", "Mittel: Nebenwirkungen müssen aktiv moderiert werden.", "Hoch: Widerstand oder Governance-Probleme wahrscheinlich.", "Sehr hoch: Vertrauen, Beteiligung oder Datenschutz können destabilisiert werden."]
  };
  return map[kind]?.[v] || "Bitte fachlich einordnen.";
}

function explainChoice(kind, value) {
  const data = {
    evidence: { niedrig: "Kaum belegt. Vor Entscheidung validieren.", mittel: "Plausibel, aber prüfbedürftig.", hoch: "Gut beobachtet oder durch mehrere Hinweise gestützt." },
    uncertainty: { niedrig: "Annahme ist relativ stabil.", mittel: "Annahme kann zutreffen, sollte aber beobachtet werden.", hoch: "Hohe Unsicherheit. Simulation stark abhängig von dieser Annahme." },
    sensitivity: { unkritisch: "Keine besondere Schutzbedürftigkeit erkennbar.", intern: "Nur intern verwenden.", vertraulich: "Vertrauliche Behandlung und sparsame Speicherung nötig.", "personenbezogen vermeiden": "Nicht als personenbezogenes Profil verwenden; anonymisieren." },
    sourceStatus: { explizit: "Im Dokument oder Auftrag ausdrücklich genannt.", abgeleitet: "Aus Kontext oder Struktur erschlossen.", Hypothese: "Beratungshypothese; unbedingt prüfen." },
    direction: { high_good: "Je höher der Wert, desto stabiler die Ressource.", low_good: "Je niedriger der Wert, desto besser. Beispiel: Zeitdruck oder Konfliktspannung." },
    trend: { steigend: "Entwickelt sich nach oben.", stabil: "Bleibt derzeit ungefähr gleich.", fallend: "Schwächt sich ab.", unklar: "Noch nicht ausreichend einschätzbar." },
    effort: { niedrig: "Mit wenig Aufwand umsetzbar.", mittel: "Benötigt Vorbereitung oder Abstimmung.", hoch: "Erfordert deutliche Ressourcen, Zeit oder Mandat." }
  };
  return data[kind]?.[value] || "Bitte fachlich prüfen und bei Bedarf überschreiben.";
}

function mkStrategy(name, description, speed, acceptance, control, innovation, risk) {
  return { id: uid(), name, description, speed, speedText: explain("speed", speed), acceptance, acceptanceText: explain("acceptance", acceptance), control, controlText: explain("control", control), innovation, innovationText: explain("innovation", innovation), risk, riskText: explain("risk", risk), conditions: "Voraussetzungen prüfen und mit Beteiligten validieren.", failureMode: "Scheitert, wenn Annahmen nicht geprüft oder Nebenwirkungen ignoriert werden.", decisionSignal: "Wählen, wenn diese Strategie am besten zur Ressourcenlage passt." };
}

const templates = [
  {
    id: "workshop-still", label: "Demo · Workshop", title: "Stille Gruppe im KI-Workshop", desc: "Stille, Hierarchie und Unsicherheit als Workshop-Szenario.",
    context: { title: "Stille Gruppe im KI-Workshop", domain: "Workshop / KI-Literacy / Organisationsentwicklung", decisionQuestion: "Wie kann ein KI-Workshop so gestaltet werden, dass stille Teilnehmende sicher in Beteiligung kommen?", goal: "Moderationsdesign, Beteiligung und psychologische Sicherheit prüfen.", boundaries: "Keine Bewertung realer Personen. Nur anonymisierte Rollenmodelle." },
    assumptions: [
      { id: uid(), text: "Die Gruppe ist nicht zwingend ablehnend, sondern wartet auf Signale von Leitung und Meinungsführenden.", source: "Vorlage Workshop", evidence: "mittel", evidenceText: explainChoice("evidence", "mittel"), uncertainty: "mittel", uncertaintyText: explainChoice("uncertainty", "mittel"), sensitivity: "intern", sensitivityText: explainChoice("sensitivity", "intern"), sourceStatus: "abgeleitet", sourceStatusText: explainChoice("sourceStatus", "abgeleitet") }
    ],
    personas: [
      { id: uid(), name: "Erfahrene Einrichtungsleitung", role: "Mittlere Führung", stance: "vorsichtig-kritisch", influence: 5, influenceText: explain("influence", 5), affectedness: 4, affectednessText: explain("affectedness", 4), trust: 3, trustText: explain("trust", 3), aiLiteracy: 2, aiLiteracyText: explain("aiLiteracy", 2), riskSense: 5, riskSenseText: explain("riskSense", 5), changeEnergy: 2, changeEnergyText: explain("changeEnergy", 2), informalRole: "Meinungsführer*in", conflictStyle: "abwartend", trigger: "Mehrarbeit, Datenschutz, Entwertung von Erfahrung", learningNeed: "Praxisnähe", communicationNeed: "Skepsis ausdrücklich legitimieren" },
      { id: uid(), name: "KI-affine Bereichsleitung", role: "Projektleitung", stance: "zustimmend", influence: 4, influenceText: explain("influence", 4), affectedness: 3, affectednessText: explain("affectedness", 3), trust: 4, trustText: explain("trust", 4), aiLiteracy: 4, aiLiteracyText: explain("aiLiteracy", 4), riskSense: 3, riskSenseText: explain("riskSense", 3), changeEnergy: 5, changeEnergyText: explain("changeEnergy", 5), informalRole: "Treiber*in", conflictStyle: "lösungsorientiert", trigger: "zu viel Grundsatzdebatte", learningNeed: "konkrete Use Cases", communicationNeed: "nicht als Gegenpol zur Skepsis inszenieren" }
    ],
    resources: [
      { id: uid(), name: "Aufmerksamkeit", type: "kognitiv", current: 3, currentText: explain("current", 3), target: 4, targetText: explain("target", 4), direction: "high_good", directionText: explainChoice("direction", "high_good"), trend: "fallend", trendText: explainChoice("trend", "fallend"), bottleneck: "zu lange Inputphasen", owner: "Moderation" },
      { id: uid(), name: "psychologische Sicherheit", type: "sozial", current: 2, currentText: explain("current", 2), target: 4, targetText: explain("target", 4), direction: "high_good", directionText: explainChoice("direction", "high_good"), trend: "fallend", trendText: explainChoice("trend", "fallend"), bottleneck: "Angst, sich mit Skepsis zu exponieren", owner: "Moderation" }
    ],
    interventions: [
      { id: uid(), name: "Einzelreflexion vor Plenum", timing: "Einstieg", timingText: "Aktivierung mit geringer Sichtbarkeit.", target: "niedrigschwellige Beteiligung", benefit: "reduziert Druck", sideEffect: "kostet Zeit", effort: "niedrig", effortText: explainChoice("effort", "niedrig") }
    ],
    strategies: [mkStrategy("A Moderierte Klärung", "Interessen, Sorgen, Rollen und Grenzen klären.", 3, 4, 4, 3, 2), mkStrategy("B Pilot-first", "Mit einem kleinen Praxisfall starten und auswerten.", 4, 4, 3, 5, 3)],
    openQuestions: ["Welche Personen setzen informell den Ton?"], warnings: ["Stille nicht als Zustimmung interpretieren."]
  },
  {
    id: "mav-governance", label: "Demo · Governance", title: "MAV-Beteiligung bei Personalführung", desc: "Führung, MAV, Dokumentation und Fristen.",
    context: { title: "MAV-Beteiligung bei Personalführung rechtssicher gestalten", domain: "Führung / Arbeitsrecht / MAV / Governance", decisionQuestion: "Wie können Führungskräfte rechtliche Vorgaben, MAV-Beteiligung und vertrauensvolle Personalführung zusammenbringen?", goal: "Handlungssicherheit erhöhen und Rollen klären.", boundaries: "Kein Ersatz für Rechtsberatung. Keine Bewertung konkreter Personen." },
    assumptions: [{ id: uid(), text: "Führungskräfte benötigen sichere Orientierung zu Schwellen, Rollen und Eskalationspunkten.", source: "Webinar-Konzept", evidence: "mittel", evidenceText: explainChoice("evidence", "mittel"), uncertainty: "mittel", uncertaintyText: explainChoice("uncertainty", "mittel"), sensitivity: "intern", sensitivityText: explainChoice("sensitivity", "intern"), sourceStatus: "abgeleitet", sourceStatusText: explainChoice("sourceStatus", "abgeleitet") }],
    personas: [{ id: uid(), name: "MAV-Rolle", role: "MAV / Interessenvertretung", stance: "schutzorientiert", influence: 5, influenceText: explain("influence", 5), affectedness: 4, affectednessText: explain("affectedness", 4), trust: 3, trustText: explain("trust", 3), aiLiteracy: 2, aiLiteracyText: explain("aiLiteracy", 2), riskSense: 5, riskSenseText: explain("riskSense", 5), changeEnergy: 3, changeEnergyText: explain("changeEnergy", 3), informalRole: "Frühwarnrolle", conflictStyle: "interessenklärend", trigger: "späte Beteiligung", learningNeed: "Rollenklärung", communicationNeed: "früh einbinden" }],
    resources: [{ id: uid(), name: "Rechtssicherheit", type: "governance", current: 3, currentText: explain("current", 3), target: 5, targetText: explain("target", 5), direction: "high_good", directionText: explainChoice("direction", "high_good"), trend: "unklar", trendText: explainChoice("trend", "unklar"), bottleneck: "uneinheitliche Anwendung", owner: "HR / Rechtsberatung" }],
    interventions: [{ id: uid(), name: "Jour fixe Dienststellenleitung–MAV", timing: "regelmäßig", timingText: "Regelmäßige Klärung senkt Überraschungen.", target: "Vertrauen und Rollenklärung", benefit: "reduziert Eskalationen", sideEffect: "braucht Agenda", effort: "mittel", effortText: explainChoice("effort", "mittel") }],
    strategies: [mkStrategy("A Schulung-first", "Führungskräfte werden durch Webinar und Checklisten handlungssicher.", 3, 4, 4, 3, 2), mkStrategy("B Prozess-first", "Prozess, Fristen und Dokumentationsstandards zuerst klären.", 2, 3, 5, 2, 2)],
    openQuestions: ["Wo beginnt Beteiligung früh genug?"], warnings: ["Nicht als Rechtsberatungstool missverstehen."]
  }
];

function cloneScenario(t) { return JSON.parse(JSON.stringify(t)); }
const initialScenario = cloneScenario(templates[0]);
function safeArray(x) { return Array.isArray(x) ? x : []; }
function normalizeDraft(draft) {
  const d = draft || {};
  return {
    context: { ...initialScenario.context, ...(d.context || {}) },
    assumptions: safeArray(d.assumptions).map(x => ({ id: uid(), source: "Import", evidence: "mittel", evidenceText: explainChoice("evidence", "mittel"), uncertainty: "mittel", uncertaintyText: explainChoice("uncertainty", "mittel"), sensitivity: "intern", sensitivityText: explainChoice("sensitivity", "intern"), sourceStatus: "abgeleitet", sourceStatusText: explainChoice("sourceStatus", "abgeleitet"), ...x })),
    personas: safeArray(d.personas).map(x => ({ id: uid(), influence: 3, influenceText: explain("influence", 3), affectedness: 3, affectednessText: explain("affectedness", 3), trust: 3, trustText: explain("trust", 3), aiLiteracy: 3, aiLiteracyText: explain("aiLiteracy", 3), riskSense: 3, riskSenseText: explain("riskSense", 3), changeEnergy: 3, changeEnergyText: explain("changeEnergy", 3), ...x })),
    resources: safeArray(d.resources).map(x => ({ id: uid(), current: 3, currentText: explain("current", 3), target: 4, targetText: explain("target", 4), direction: "high_good", directionText: explainChoice("direction", "high_good"), trend: "unklar", trendText: explainChoice("trend", "unklar"), ...x })),
    interventions: safeArray(d.interventions).map(x => ({ id: uid(), effort: "mittel", effortText: explainChoice("effort", "mittel"), timingText: "Zeitpunkt fachlich prüfen.", ...x })),
    strategies: safeArray(d.strategies).map(x => ({ id: uid(), speedText: x.speedText || explain("speed", x.speed || 3), acceptanceText: x.acceptanceText || explain("acceptance", x.acceptance || 3), controlText: x.controlText || explain("control", x.control || 3), innovationText: x.innovationText || explain("innovation", x.innovation || 3), riskText: x.riskText || explain("risk", x.risk || 3), ...x })),
    openQuestions: safeArray(d.openQuestions), warnings: safeArray(d.warnings)
  };
}

function avg(list, key) { return list.length ? list.reduce((s, x) => s + Number(x[key] || 0), 0) / list.length : 0; }
function resourceScore(r) { return (r.direction === "low_good" ? 6 - Number(r.current || 1) : Number(r.current || 1)) * 20; }
function resourceGap(r) { return r.direction === "low_good" ? Number(r.current || 1) - Number(r.target || 1) : Number(r.target || 1) - Number(r.current || 1); }
function strategyScore(s) { return Number(s.acceptance || 0) * 3 + Number(s.control || 0) * 3 + Number(s.innovation || 0) * 2 + Number(s.speed || 0) - Number(s.risk || 0) * 3; }
function compute(s) {
  const resources=safeArray(s.resources), personas=safeArray(s.personas), assumptions=safeArray(s.assumptions), interventions=safeArray(s.interventions), strategies=safeArray(s.strategies);
  const res=resources.length?resources.reduce((a,r)=>a+resourceScore(r),0)/resources.length:60;
  const risky=assumptions.filter(a=>a.evidence==="niedrig"||a.uncertainty==="hoch");
  const hasPrivacy=interventions.some(i=>/daten|datenschutz|grenze|faq|dokumentation/i.test(`${i.name} ${i.target}`));
  const hasParticipation=interventions.some(i=>/einwand|beteilig|freiwillig|workshop|jour fixe|rollenklärung|reflexion/i.test(`${i.name} ${i.target}`));
  const acceptance=Math.round(Math.min(100,20+avg(personas,"trust")*8+avg(personas,"aiLiteracy")*3+avg(personas,"changeEnergy")*4+(hasParticipation?16:0)+res*.15-risky.length*4));
  const governance=Math.round(Math.min(100,30+avg(personas,"riskSense")*5+(hasPrivacy?22:0)+res*.18));
  const learning=Math.round(Math.min(100,25+avg(personas,"aiLiteracy")*7+avg(personas,"changeEnergy")*5+interventions.length*5));
  const risk=Math.round(Math.max(0,100-(acceptance*.35+governance*.4+learning*.15+res*.1)));
  const bestStrategy=[...strategies].sort((a,b)=>strategyScore(b)-strategyScore(a))[0];
  return {acceptance,governance,learning,resources:Math.round(res),risk,risky,deficits:resources.filter(r=>resourceGap(r)>0),bestStrategy};
}
function loadSaved(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")}catch{return[]}}
function persistSaved(items){localStorage.setItem(STORAGE_KEY,JSON.stringify(items))}
function reportTitle(key){const m={executiveSummary:"Executive Summary",ausgangslage:"Ausgangslage",simulationsannahmen:"Simulationsannahmen",stakeholderanalyse:"Persona- und Stakeholderanalyse",ressourcenRisikolage:"Ressourcen- und Risikolage",phasenanalyse:"Phasenanalyse",konfliktKoalitionsmuster:"Konflikt- und Koalitionsmuster",kritischeKipppunkte:"Kritische Kipppunkte",interventionsoptionen:"Interventionsoptionen",entscheidungsmatrix:"Entscheidungsmatrix",massnahmenplan:"Maßnahmenplan",offeneFragen:"Offene Fragen",governanceHinweise:"Datenschutz-/Governance-Hinweise",grenzenDerSimulation:"Grenzen der Simulation"};return m[key]||key}

function Card({children,className=""}){return <section className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-sm ${className}`}>{children}</section>}
function Button({children,onClick,dark=false,disabled=false}){return <button disabled={disabled} onClick={onClick} className={`${dark?"bg-slate-900 text-white":"bg-white text-slate-800 border border-slate-200"} rounded-xl px-3 py-2 text-sm font-bold disabled:opacity-50`}>{children}</button>}
function Field({label,value,onChange,area=false}){const c="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:ring-4 focus:ring-slate-100";return <label className="block"><span className="mb-1 block text-sm font-semibold text-slate-700">{label}</span>{area?<textarea className={`${c} min-h-24`} value={value||""} onChange={e=>onChange(e.target.value)}/>:<input className={c} value={value||""} onChange={e=>onChange(e.target.value)}/>}</label>}
function SelectField({label,value,onChange,options}){return <label className="block"><span className="mb-1 block text-sm font-semibold text-slate-700">{label}</span><select className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm" value={value||""} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o} value={o}>{o}</option>)}</select></label>}
function RangeText({label,value,onChange,text,kind}){return <div className="rounded-xl border bg-white p-3"><label><div className="mb-1 flex justify-between text-sm"><b>{label}</b><span>{value||3}/5</span></div><input type="range" min="1" max="5" value={value||3} onChange={e=>{const v=Number(e.target.value);onChange(v, explain(kind,v))}} className="w-full accent-slate-900"/></label><textarea className="mt-2 min-h-20 w-full rounded-xl border bg-slate-50 p-2 text-xs leading-5" value={text||""} onChange={e=>onChange(value||3,e.target.value)}/></div>}
function ChoiceText({label,value,onChange,text,kind,options}){return <div><SelectField label={label} value={value} options={options} onChange={v=>onChange(v, explainChoice(kind,v))}/><textarea className="mt-2 min-h-16 w-full rounded-xl border bg-slate-50 p-2 text-xs leading-5" value={text||""} onChange={e=>onChange(value,e.target.value)}/></div>}
function Mini({title,text}){return <div className="rounded-xl bg-white p-3"><b>{title}</b><p className="mt-2 whitespace-pre-line text-sm text-slate-600">{text||"—"}</p></div>}

function Templates({setState,setTab}){return <Card><h2 className="text-xl font-bold">Standardszenarien</h2><p className="mt-1 text-sm text-slate-600">Vorlagen zum Starten, Demonstrieren und Weiterarbeiten.</p><div className="mt-4 grid gap-4 lg:grid-cols-2">{templates.map(s=><div className="rounded-2xl border bg-slate-50 p-4" key={s.id}><div className="mb-2 inline-flex rounded-full bg-white px-3 py-1 text-xs font-bold">{s.label}</div><h3 className="font-bold">{s.title}</h3><p className="mt-2 text-sm text-slate-600">{s.desc}</p><div className="mt-3"><Button dark onClick={()=>{setState(cloneScenario(s));setTab("Ausgangslage")}}>Vorlage laden</Button></div></div>)}</div></Card>}
function Dashboard({sim}){const rows=[["Akzeptanz",sim.acceptance],["Governance",sim.governance],["Ressourcen",sim.resources],["Lernfähigkeit",sim.learning],["Restrisiko",sim.risk]];return <Card><h2 className="text-xl font-bold">Dashboard</h2><div className="mt-4 grid gap-3 md:grid-cols-5">{rows.map(([k,v])=><div className="rounded-2xl border bg-slate-50 p-4" key={k}><div className="text-sm font-semibold text-slate-500">{k}</div><div className="text-3xl font-bold">{v}</div><div className="mt-2 h-2 rounded bg-slate-200"><div className="h-2 rounded bg-slate-900" style={{width:`${Math.max(0,Math.min(100,v))}%`}}/></div></div>)}</div><p className="mt-4 text-sm text-slate-600">Empfohlene Strategie: <b>{sim.bestStrategy?.name||"keine"}</b></p></Card>}
function Context({state,setState}){const u=(k,v)=>setState(s=>({...s,context:{...s.context,[k]:v}}));return <Card><h2 className="text-xl font-bold">Ausgangslage</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Titel" value={state.context.title} onChange={v=>u("title",v)}/><Field label="Domäne" value={state.context.domain} onChange={v=>u("domain",v)}/><div className="md:col-span-2"><Field area label="Entscheidungsfrage" value={state.context.decisionQuestion} onChange={v=>u("decisionQuestion",v)}/></div><Field area label="Ziel" value={state.context.goal} onChange={v=>u("goal",v)}/><Field area label="Grenzen / Nicht-Zwecke" value={state.context.boundaries} onChange={v=>u("boundaries",v)}/></div></Card>}

function Assumptions({items,setItems}){const upd=(id,patch)=>setItems(prev=>prev.map(x=>x.id===id?{...x,...patch}:x));return <Card><div className="flex justify-between"><h2 className="text-xl font-bold">Annahmen</h2><Button dark onClick={()=>setItems(prev=>[...prev,{id:uid(),text:"Neue Annahme",source:"manuell",evidence:"niedrig",evidenceText:explainChoice("evidence","niedrig"),uncertainty:"mittel",uncertaintyText:explainChoice("uncertainty","mittel"),sensitivity:"intern",sensitivityText:explainChoice("sensitivity","intern"),sourceStatus:"Hypothese",sourceStatusText:explainChoice("sourceStatus","Hypothese")}])}>+ Hinzufügen</Button></div><div className="mt-4 space-y-4">{items.map(a=><div className="rounded-2xl border bg-slate-50 p-4" key={a.id}><div className="grid gap-4 md:grid-cols-2"><Field area label="Annahme" value={a.text} onChange={v=>upd(a.id,{text:v})}/><Field label="Quelle" value={a.source} onChange={v=>upd(a.id,{source:v})}/><ChoiceText label="Evidenz" value={a.evidence} text={a.evidenceText} kind="evidence" options={menu.evidence} onChange={(v,t)=>upd(a.id,{evidence:v,evidenceText:t})}/><ChoiceText label="Unsicherheit" value={a.uncertainty} text={a.uncertaintyText} kind="uncertainty" options={menu.uncertainty} onChange={(v,t)=>upd(a.id,{uncertainty:v,uncertaintyText:t})}/><ChoiceText label="Sensibilität" value={a.sensitivity} text={a.sensitivityText} kind="sensitivity" options={menu.sensitivity} onChange={(v,t)=>upd(a.id,{sensitivity:v,sensitivityText:t})}/><ChoiceText label="Status" value={a.sourceStatus} text={a.sourceStatusText} kind="sourceStatus" options={menu.sourceStatus} onChange={(v,t)=>upd(a.id,{sourceStatus:v,sourceStatusText:t})}/></div><button className="mt-3 text-sm font-bold text-rose-700" onClick={()=>setItems(prev=>prev.filter(x=>x.id!==a.id))}>löschen</button></div>)}</div></Card>}
function Personas({items,setItems}){const upd=(id,patch)=>setItems(prev=>prev.map(x=>x.id===id?{...x,...patch}:x));return <Card><div className="flex justify-between"><h2 className="text-xl font-bold">Personas</h2><Button dark onClick={()=>setItems(prev=>[...prev,{id:uid(),name:"Neue Rolle",role:"Stakeholder",stance:"unklar",informalRole:"keine besondere informelle Rolle",conflictStyle:"unklar",influence:3,influenceText:explain("influence",3),affectedness:3,affectednessText:explain("affectedness",3),trust:3,trustText:explain("trust",3),aiLiteracy:3,aiLiteracyText:explain("aiLiteracy",3),riskSense:3,riskSenseText:explain("riskSense",3),changeEnergy:3,changeEnergyText:explain("changeEnergy",3),trigger:"",learningNeed:"",communicationNeed:""}])}>+ Hinzufügen</Button></div><div className="mt-4 space-y-4">{items.map(p=><div className="rounded-2xl border bg-slate-50 p-4" key={p.id}><div className="grid gap-4 md:grid-cols-2"><Field label="Name" value={p.name} onChange={v=>upd(p.id,{name:v})}/><SelectField label="Rolle" value={p.role} onChange={v=>upd(p.id,{role:v})} options={menu.role}/><SelectField label="Haltung" value={p.stance} onChange={v=>upd(p.id,{stance:v})} options={menu.stance}/><SelectField label="Informelle Rolle" value={p.informalRole} onChange={v=>upd(p.id,{informalRole:v})} options={menu.informalRole}/><SelectField label="Konfliktstil" value={p.conflictStyle} onChange={v=>upd(p.id,{conflictStyle:v})} options={menu.conflictStyle}/><Field label="Trigger" value={p.trigger} onChange={v=>upd(p.id,{trigger:v})}/>{[["influence","Einfluss","influenceText"],["affectedness","Betroffenheit","affectednessText"],["trust","Vertrauen","trustText"],["aiLiteracy","KI-Kompetenz","aiLiteracyText"],["riskSense","Risikoempfinden","riskSenseText"],["changeEnergy","Veränderungsenergie","changeEnergyText"]].map(([k,l,tk])=><RangeText key={k} label={l} value={p[k]} text={p[tk]} kind={k} onChange={(v,t)=>upd(p.id,{[k]:v,[tk]:t})}/>) }<Field area label="Lernbedarf" value={p.learningNeed} onChange={v=>upd(p.id,{learningNeed:v})}/><Field area label="Kommunikationsbedarf" value={p.communicationNeed} onChange={v=>upd(p.id,{communicationNeed:v})}/></div><button className="mt-3 text-sm font-bold text-rose-700" onClick={()=>setItems(prev=>prev.filter(x=>x.id!==p.id))}>löschen</button></div>)}</div></Card>}
function Resources({items,setItems}){const upd=(id,patch)=>setItems(prev=>prev.map(x=>x.id===id?{...x,...patch}:x));return <Card><div className="flex justify-between"><h2 className="text-xl font-bold">Ressourcen</h2><Button dark onClick={()=>setItems(prev=>[...prev,{id:uid(),name:"Neue Ressource",type:"sozial",current:3,currentText:explain("current",3),target:4,targetText:explain("target",4),direction:"high_good",directionText:explainChoice("direction","high_good"),trend:"stabil",trendText:explainChoice("trend","stabil"),bottleneck:"",owner:""}])}>+ Hinzufügen</Button></div><div className="mt-4 space-y-4">{items.map(r=><div className="rounded-2xl border bg-slate-50 p-4" key={r.id}><div className="grid gap-4 md:grid-cols-2"><Field label="Ressource" value={r.name} onChange={v=>upd(r.id,{name:v})}/><SelectField label="Typ" value={r.type} onChange={v=>upd(r.id,{type:v})} options={menu.resourceType}/><ChoiceText label="Logik" value={r.direction} text={r.directionText} kind="direction" options={menu.direction} onChange={(v,t)=>upd(r.id,{direction:v,directionText:t})}/><ChoiceText label="Trend" value={r.trend} text={r.trendText} kind="trend" options={menu.trend} onChange={(v,t)=>upd(r.id,{trend:v,trendText:t})}/><RangeText label="Aktueller Wert" value={r.current} text={r.currentText} kind="current" onChange={(v,t)=>upd(r.id,{current:v,currentText:t})}/><RangeText label="Zielwert" value={r.target} text={r.targetText} kind="target" onChange={(v,t)=>upd(r.id,{target:v,targetText:t})}/><Field area label="Engpass / Kipprisiko" value={r.bottleneck} onChange={v=>upd(r.id,{bottleneck:v})}/><Field area label="Beobachten / Verantwortlich" value={r.owner} onChange={v=>upd(r.id,{owner:v})}/></div><button className="mt-3 text-sm font-bold text-rose-700" onClick={()=>setItems(prev=>prev.filter(x=>x.id!==r.id))}>löschen</button></div>)}</div></Card>}
function Interventions({items,setItems}){const upd=(id,patch)=>setItems(prev=>prev.map(x=>x.id===id?{...x,...patch}:x));return <Card><div className="flex justify-between"><h2 className="text-xl font-bold">Interventionen</h2><Button dark onClick={()=>setItems(prev=>[...prev,{id:uid(),name:"Neue Intervention",timing:"offen",timingText:"Zeitpunkt fachlich prüfen.",target:"",benefit:"",sideEffect:"",effort:"mittel",effortText:explainChoice("effort","mittel")}])}>+ Hinzufügen</Button></div><div className="mt-4 space-y-4">{items.map(i=><div className="rounded-2xl border bg-slate-50 p-4" key={i.id}><div className="grid gap-4 md:grid-cols-2"><Field label="Name" value={i.name} onChange={v=>upd(i.id,{name:v})}/><SelectField label="Zeitpunkt" value={i.timing} onChange={v=>upd(i.id,{timing:v,timingText:`Intervention im Abschnitt „${v}“ einplanen und mit Ziel sowie Nebenwirkung prüfen.`})} options={menu.timing}/><Field area label="Zeitpunkt-Begründung" value={i.timingText} onChange={v=>upd(i.id,{timingText:v})}/><Field label="Ziel" value={i.target} onChange={v=>upd(i.id,{target:v})}/><Field area label="Nutzen" value={i.benefit} onChange={v=>upd(i.id,{benefit:v})}/><Field area label="Nebenwirkung" value={i.sideEffect} onChange={v=>upd(i.id,{sideEffect:v})}/><ChoiceText label="Aufwand" value={i.effort} text={i.effortText} kind="effort" options={menu.effort} onChange={(v,t)=>upd(i.id,{effort:v,effortText:t})}/></div><button className="mt-3 text-sm font-bold text-rose-700" onClick={()=>setItems(prev=>prev.filter(x=>x.id!==i.id))}>löschen</button></div>)}</div></Card>}
function Strategies({items,setItems}){const upd=(id,patch)=>setItems(prev=>prev.map(x=>x.id===id?{...x,...patch}:x));return <Card><h2 className="text-xl font-bold">Strategien</h2><p className="text-sm text-slate-600">Slider ändern automatisch die Begründungstexte; alle Subtexte bleiben überschreibbar.</p><div className="mt-4 space-y-4">{items.map(st=><div className="rounded-2xl border bg-slate-50 p-4" key={st.id}><Field label="Name" value={st.name} onChange={v=>upd(st.id,{name:v})}/><div className="mt-3"><Field area label="Grundidee" value={st.description} onChange={v=>upd(st.id,{description:v})}/></div><div className="mt-4 grid gap-3 lg:grid-cols-5">{[["speed","Tempo","speedText"],["acceptance","Akzeptanz","acceptanceText"],["control","Kontrolle","controlText"],["innovation","Innovation","innovationText"],["risk","Risiko","riskText"]].map(([k,l,tk])=><RangeText key={k} label={l} value={st[k]} text={st[tk]} kind={k} onChange={(v,t)=>upd(st.id,{[k]:v,[tk]:t})}/>)}</div><div className="mt-3 grid gap-3 md:grid-cols-3"><Field area label="Bedingungen" value={st.conditions} onChange={v=>upd(st.id,{conditions:v})}/><Field area label="Scheiternsmodus" value={st.failureMode} onChange={v=>upd(st.id,{failureMode:v})}/><Field area label="Entscheidungssignal" value={st.decisionSignal} onChange={v=>upd(st.id,{decisionSignal:v})}/></div></div>)}</div></Card>}
function ImportPanel({setState,setTab}){const [text,setText]=useState("");const [draft,setDraft]=useState(null);const [documentType,setDocumentType]=useState("Konzept");const [analysisMode,setAnalysisMode]=useState("beratend");const [status,setStatus]=useState("idle");const [err,setErr]=useState("");async function runImport(){setStatus("loading");setErr("");try{const res=await fetch("/api/import-scenario",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,documentType,analysisMode})});if(!res.ok)throw new Error(await res.text());setDraft(normalizeDraft(await res.json()));setStatus("done")}catch(e){setErr(String(e.message||e));setStatus("error")}}async function file(e){const f=e.target.files?.[0];if(!f)return;if(f.size>1024*1024){setErr("Datei größer als 1 MB.");return}if(!f.name.toLowerCase().match(/\.(txt|md|json)$/)&&!f.type.startsWith("text/")){setErr("Upload Light unterstützt aktuell TXT, MD, JSON und reine Textdateien.");return}setText(await f.text())}return <Card><h2 className="text-xl font-bold">Import Light</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><SelectField label="Dokumenttyp" value={documentType} onChange={setDocumentType} options={menu.documentType}/><SelectField label="Analysemodus" value={analysisMode} onChange={setAnalysisMode} options={menu.analysisMode}/><label><span className="mb-1 block text-sm font-semibold">Datei hochladen</span><input type="file" accept=".txt,.md,.json,text/*" onChange={file} className="w-full rounded-xl border bg-white p-2 text-sm"/></label></div><textarea className="mt-4 min-h-64 w-full rounded-2xl border p-4 text-sm" value={text} onChange={e=>setText(e.target.value)} placeholder="Konzepttext einfügen oder Textdatei hochladen."/><div className="mt-3 flex gap-2"><Button dark disabled={status==="loading"||text.trim().length<80} onClick={runImport}>{status==="loading"?"Analysiere ...":"Szenarioentwurf erzeugen"}</Button>{draft&&<Button onClick={()=>setDraft(null)}>Entwurf verwerfen</Button>}</div>{err&&<div className="mt-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{err}</div>}{draft&&<div className="mt-5 rounded-2xl border bg-slate-50 p-4"><h3 className="font-bold">Review vor Übernahme</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><Mini title="Ausgangslage" text={`${draft.context.title}\n${draft.context.decisionQuestion}`}/><Mini title="Offene Fragen" text={draft.openQuestions.join("\n")}/></div><div className="mt-4"><Button dark onClick={()=>{setState(draft);setDraft(null);setTab("Ausgangslage")}}>Entwurf übernehmen</Button></div></div>}</Card>}
function Report({state,sim}){const [status,setStatus]=useState("local"),[gpt,setGpt]=useState(null);async function run(){setStatus("loading");try{const r=await fetch("/api/simulate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({state})});if(!r.ok)throw new Error(await r.text());setGpt(await r.json());setStatus("done")}catch{setStatus("error")}}const sections=gpt?Object.entries(gpt).map(([k,v])=>[reportTitle(k),v]):[["Executive Summary",`${state.context.title}\nAkzeptanz ${sim.acceptance}, Governance ${sim.governance}, Ressourcen ${sim.resources}, Restrisiko ${sim.risk}.`],["Ressourcenengpässe",sim.deficits.map(r=>`${r.name}: ${r.bottleneck}`).join("\n")||"keine"],["Riskante Annahmen",sim.risky.map(a=>a.text).join("\n")||"keine"],["Strategie",sim.bestStrategy?.name||"keine"]];return <Card><div className="flex justify-between"><h2 className="text-xl font-bold">Report</h2><div className="flex gap-2"><Button onClick={run}>GPT-Report</Button><Button dark onClick={()=>navigator.clipboard?.writeText(sections.map(([a,b])=>`${a}\n${b}`).join("\n\n"))}>Kopieren</Button></div></div><p className="mt-2 text-sm text-slate-500">Status: {status}</p><div className="mt-4 grid gap-3 md:grid-cols-2">{sections.map(([k,v])=><div className="rounded-2xl border bg-slate-50 p-4" key={k}><b>{k}</b><p className="mt-2 whitespace-pre-line text-sm">{String(v)}</p></div>)}</div></Card>}
function Storage({state,setState,saved,setSaved}){const [name,setName]=useState(state.context.title);function save(){const item={id:uid(),name:name||state.context.title,date:new Date().toISOString(),state};const next=[item,...saved];setSaved(next);persistSaved(next)}function load(item){setState(item.state)}function duplicate(item){const next=[{id:uid(),name:item.name+" Kopie",date:new Date().toISOString(),state:item.state},...saved];setSaved(next);persistSaved(next)}function del(id){const next=saved.filter(x=>x.id!==id);setSaved(next);persistSaved(next)}return <Card><h2 className="text-xl font-bold">Speichern und Laden</h2><div className="mt-4 flex gap-2"><input className="flex-1 rounded-xl border p-2" value={name} onChange={e=>setName(e.target.value)}/><Button dark onClick={save}>Aktuelles Szenario speichern</Button></div><div className="mt-4 space-y-3">{saved.map(item=><div className="rounded-2xl border bg-slate-50 p-4" key={item.id}><b>{item.name}</b><div className="text-xs text-slate-500">{new Date(item.date).toLocaleString()}</div><div className="mt-2 flex gap-2"><Button onClick={()=>load(item)}>Laden</Button><Button onClick={()=>duplicate(item)}>Duplizieren</Button><Button onClick={()=>del(item.id)}>Löschen</Button></div></div>)}</div></Card>}
function Compare({saved}){const [a,setA]=useState(""),[b,setB]=useState("");const A=saved.find(x=>x.id===a)?.state,B=saved.find(x=>x.id===b)?.state;const ca=A?compute(A):null,cb=B?compute(B):null;return <Card><h2 className="text-xl font-bold">Vergleich</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><select className="rounded-xl border p-2" value={a} onChange={e=>setA(e.target.value)}><option value="">Simulation A wählen</option>{saved.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select className="rounded-xl border p-2" value={b} onChange={e=>setB(e.target.value)}><option value="">Simulation B wählen</option>{saved.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>{ca&&cb&&<table className="mt-4 w-full text-sm"><thead><tr><th className="p-2 text-left">Kriterium</th><th>A</th><th>B</th><th>Delta</th></tr></thead><tbody>{[["Akzeptanz","acceptance"],["Governance","governance"],["Ressourcen","resources"],["Lernfähigkeit","learning"],["Restrisiko","risk"]].map(([l,k])=><tr className="border-t" key={k}><td className="p-2 font-semibold">{l}</td><td>{ca[k]}</td><td>{cb[k]}</td><td>{cb[k]-ca[k]}</td></tr>)}</tbody></table>}</Card>}

const tabs=["Dashboard","Vorlagen","Import","Ausgangslage","Annahmen","Personas","Ressourcen","Interventionen","Strategien","Report","Speicher","Vergleich"];
export default function App(){const [state,setState]=useState(initialScenario);const [tab,setTab]=useState("Vorlagen");const [saved,setSaved]=useState([]);useEffect(()=>setSaved(loadSaved()),[]);const sim=useMemo(()=>compute(state),[state]);const set=(key,val)=>setState(s=>({...s,[key]: typeof val === "function" ? val(s[key] || []) : val}));const views={Dashboard:<Dashboard sim={sim}/>,Vorlagen:<Templates setState={setState} setTab={setTab}/>,Import:<ImportPanel setState={setState} setTab={setTab}/>,Ausgangslage:<Context state={state} setState={setState}/>,Annahmen:<Assumptions items={state.assumptions} setItems={v=>set("assumptions",v)}/>,Personas:<Personas items={state.personas} setItems={v=>set("personas",v)}/>,Ressourcen:<Resources items={state.resources} setItems={v=>set("resources",v)}/>,Interventionen:<Interventions items={state.interventions} setItems={v=>set("interventions",v)}/>,Strategien:<Strategies items={state.strategies} setItems={v=>set("strategies",v)}/>,Report:<Report state={state} sim={sim}/>,Speicher:<Storage state={state} setState={setState} saved={saved} setSaved={setSaved}/>,Vergleich:<Compare saved={saved}/>};return <main className="min-h-screen bg-slate-100 p-4 text-slate-900 md:p-8"><div className="mx-auto max-w-7xl space-y-5"><header className="rounded-3xl bg-slate-950 p-8 text-white"><div className="mb-3 inline-flex rounded-full border border-white/20 px-3 py-1 text-sm">KI-Kernel GPT 0.6</div><h1 className="text-4xl font-bold">Geführte Szenariomodellierung</h1><p className="mt-3 max-w-3xl text-slate-300">Sliderwerte und Subtexte werden jetzt gemeinsam gespeichert. Menüs und Subtexte bleiben überschreibbar.</p><div className="mt-5 flex gap-3"><Button onClick={()=>{setState(cloneScenario(templates[0]));setTab("Ausgangslage")}}>Demo neu laden</Button><a className="rounded-xl border border-white/20 bg-white/10 px-3 py-2 text-sm font-bold" href="/hilfe.html" target="_blank" rel="noreferrer">Hilfe öffnen</a></div></header><nav className="sticky top-2 z-10 overflow-x-auto rounded-2xl border bg-white/90 p-2 shadow-sm backdrop-blur"><div className="flex min-w-max gap-2">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl px-3 py-2 text-sm font-bold ${tab===t?"bg-slate-900 text-white":"text-slate-600 hover:bg-slate-100"}`}>{t}</button>)}<a href="/hilfe.html" target="_blank" rel="noreferrer" className="rounded-xl px-3 py-2 text-sm font-bold text-slate-600 hover:bg-slate-100">Hilfe</a></div></nav>{views[tab]}<footer className="rounded-2xl border bg-white p-4 text-xs text-slate-500">Alle automatisch erzeugten Subtexte sind überschreibbar. Speicherung erfolgt lokal im Browser. Keine echten personenbezogenen Profile verwenden.</footer></div></main>}
