import React, { useEffect, useMemo, useState } from "react";

const uid = () => Math.random().toString(36).slice(2, 10);
const STORAGE_KEY = "ki-kernel-scenarios-v7";
const copy = (x) => JSON.parse(JSON.stringify(x));

const menu = {
  evidence: ["niedrig", "mittel", "hoch"],
  uncertainty: ["niedrig", "mittel", "hoch"],
  sensitivity: ["unkritisch", "intern", "vertraulich", "personenbezogen vermeiden"],
  sourceStatus: ["explizit", "abgeleitet", "Hypothese"],
  role: ["Operative Praxis", "Mittlere Führung", "Geschäftsführung", "Projektleitung", "Governance", "Datenschutz", "MAV / Interessenvertretung", "QM / Prozesssteuerung", "Pädagogik", "Verwaltung", "Finanzierung", "Lerngruppe", "Stakeholder", "Sonstige Rolle"],
  stance: ["zustimmend", "experimentierfreudig", "offen, aber überlastet", "pragmatisch", "vermittelnd", "strukturierend", "prüfend", "prüfend und begrenzend", "schutzorientiert", "vorsichtig-kritisch", "skeptisch", "distanziert", "unsicher", "unklar"],
  conflictStyle: ["vermeidend", "abwartend", "kritisch nachfragend", "werteorientiert", "regelbasiert", "interessenklärend", "argumentativ", "konfrontativ", "ausgleichend", "moderierend", "lösungsorientiert", "steuernd", "unklar"],
  informalRole: ["Meinungsführer*in", "Brückenrolle", "Stoppsignal", "Treiber*in", "Realitätscheck", "Prozessanker", "Frühwarnrolle", "Seismograf für Klima", "Veto-Risiko", "formale Entscheidung", "informelle Macht", "keine besondere informelle Rolle"],
  resourceType: ["sozial", "kognitiv", "emotional", "operativ", "materiell", "governance", "kommunikativ", "lernbezogen"],
  direction: ["high_good", "low_good"],
  trend: ["steigend", "stabil", "fallend", "unklar"],
  timing: ["vorab", "Einstieg", "früh", "Mitte", "Entscheidung", "Abschluss", "nachgelagert", "regelmäßig", "offen"],
  effort: ["niedrig", "mittel", "hoch"],
  documentType: ["Konzept", "Projektantrag", "Workshopplan", "Richtlinie", "Protokoll", "Strategiepapier", "Schulungskonzept", "Sonstiges"],
  analysisMode: ["vorsichtig", "beratend", "pre-mortem"]
};

function explain(kind, value) {
  const i = Math.max(1, Math.min(5, Number(value || 3))) - 1;
  const data = {
    influence: ["Sehr geringer Einfluss: wirkt kaum auf Entscheidung oder Gruppendynamik.", "Geringer Einfluss: wird gehört, prägt aber nur begrenzt.", "Mittlerer Einfluss: kann Stimmungen oder Entscheidungen mitprägen.", "Hoher Einfluss: prägt Akzeptanz, Tempo oder Widerstand deutlich.", "Sehr hoher Einfluss: Schlüsselrolle; ohne diese Rolle kippt das Szenario leicht."],
    affectedness: ["Sehr geringe Betroffenheit: nur randständig berührt.", "Geringe Betroffenheit: Auswirkungen sind vorhanden, aber begrenzt.", "Mittlere Betroffenheit: spürbare Veränderung im Alltag.", "Hohe Betroffenheit: Rolle, Verantwortung oder Routinen sind stark betroffen.", "Sehr hohe Betroffenheit: Veränderung berührt Selbstverständnis oder Arbeitsweise zentral."],
    trust: ["Sehr geringes Vertrauen: starke Schutz- oder Abwehrlogik wahrscheinlich.", "Geringes Vertrauen: Kommunikation muss zuerst Sicherheit erzeugen.", "Mittleres Vertrauen: Zustimmung hängt stark von Transparenz ab.", "Hohes Vertrauen: konstruktive Mitarbeit möglich, wenn Grenzen klar sind.", "Sehr hohes Vertrauen: stabilisierende oder multiplizierende Rolle."],
    aiLiteracy: ["Sehr geringe KI-Kompetenz: Grundlagen und Grenzen zuerst klären.", "Geringe KI-Kompetenz: einfache Beispiele und sichere Anleitung nötig.", "Mittlere KI-Kompetenz: Anwendung möglich, Begleitung bleibt wichtig.", "Hohe KI-Kompetenz: kann Use Cases entwickeln und andere unterstützen.", "Sehr hohe KI-Kompetenz: mögliche Multiplikator- oder Pilotrolle."],
    riskSense: ["Sehr geringes Risikoempfinden: Gefahr von Sorglosigkeit oder Shadow-Use.", "Geringes Risikoempfinden: Risiken müssen sichtbar gemacht werden.", "Mittleres Risikoempfinden: abwägende Haltung möglich.", "Hohes Risikoempfinden: Schutz-, Datenschutz- oder Qualitätsfragen dominieren.", "Sehr hohes Risikoempfinden: wertvolle Frühwarnrolle oder Blockadepunkt."],
    changeEnergy: ["Sehr geringe Veränderungsenergie: passive oder blockierende Dynamik möglich.", "Geringe Veränderungsenergie: Beteiligung braucht Entlastung und Sinn.", "Mittlere Veränderungsenergie: Mitgehen möglich, wenn Aufwand und Nutzen plausibel sind.", "Hohe Veränderungsenergie: kann Umsetzung aktiv unterstützen.", "Sehr hohe Veränderungsenergie: mögliche Treiber- oder Pilotrolle."],
    current: ["Sehr schwach ausgeprägt: akuter Stabilisierungsbedarf.", "Schwach ausgeprägt: Ressource ist fragil.", "Mittel ausgeprägt: tragfähig, aber beobachtungsbedürftig.", "Gut ausgeprägt: Ressource kann genutzt werden.", "Sehr stark ausgeprägt: Ressource ist ein Hebel im Szenario."],
    target: ["Minimalziel: nur basale Stabilisierung nötig.", "Niedriges Ziel: begrenzte Verbesserung reicht.", "Mittleres Ziel: solide Arbeitsfähigkeit wird angestrebt.", "Hohes Ziel: Ressource soll aktiv tragend werden.", "Sehr hohes Ziel: Ressource wird zentraler Erfolgsfaktor."],
    speed: ["Sehr langsam: lange Klärung vor Bewegung.", "Eher langsam: Sorgfalt und Beteiligung bremsen, erhöhen aber Anschlussfähigkeit.", "Mittleres Tempo: Klärung und Umsetzung halten sich die Waage.", "Eher schnell: rascher Start mit Kommunikationsbedarf.", "Sehr schnell: hoher Umsetzungsschub durch klare Entscheidung."],
    acceptance: ["Sehr geringe Akzeptanz: Vorgehen wirkt fremd oder belastend.", "Geringe Akzeptanz: Beteiligungs- und Vertrauensrisiken.", "Mittlere Akzeptanz: Zustimmung hängt stark von Kommunikation ab.", "Hohe Akzeptanz: anschlussfähig, wenn Grenzen klar bleiben.", "Sehr hohe Akzeptanz: passt gut zu Bedarf und Belastungslage."],
    control: ["Sehr geringe Kontrolle: Governance kaum steuerbar.", "Geringe Kontrolle: relevante Lücken und Nachsteuerungsbedarf.", "Mittlere Kontrolle: Grundregeln möglich, aber nicht vollständig abgesichert.", "Hohe Kontrolle: Zuständigkeiten und Datenregeln gut steuerbar.", "Sehr hohe Kontrolle: Governance und Qualitätssicherung klar angelegt."],
    innovation: ["Sehr gering: Lernen und Erprobung stark begrenzt.", "Gering: wenige neue Praxisimpulse.", "Mittel: Raum für Lernen, aber keine breite Erprobung.", "Hoch: praxisnahe Experimente wahrscheinlich.", "Sehr hoch: viele Use Cases und organisationales Lernen."],
    risk: ["Sehr gering: wenige erkennbare Nebenwirkungen.", "Gering: wichtigste Risiken wirken beherrschbar.", "Mittel: Nebenwirkungen müssen aktiv moderiert werden.", "Hoch: Widerstand oder Governance-Probleme wahrscheinlich.", "Sehr hoch: Vertrauen, Beteiligung oder Datenschutz können destabilisiert werden."]
  };
  return data[kind]?.[i] || "Bitte fachlich einordnen.";
}
function explainChoice(kind, value) {
  const data = {
    evidence: { niedrig: "Kaum belegt. Vor Entscheidung validieren.", mittel: "Plausibel, aber prüfbedürftig.", hoch: "Gut beobachtet oder durch mehrere Hinweise gestützt." },
    uncertainty: { niedrig: "Annahme ist relativ stabil.", mittel: "Annahme kann zutreffen, sollte aber beobachtet werden.", hoch: "Hohe Unsicherheit. Simulation stark abhängig von dieser Annahme." },
    sensitivity: { unkritisch: "Keine besondere Schutzbedürftigkeit erkennbar.", intern: "Nur intern verwenden.", vertraulich: "Vertraulich behandeln und sparsam speichern.", "personenbezogen vermeiden": "Nicht als personenbezogenes Profil verwenden; anonymisieren." },
    sourceStatus: { explizit: "Im Dokument oder Auftrag ausdrücklich genannt.", abgeleitet: "Aus Kontext oder Struktur erschlossen.", Hypothese: "Beratungshypothese; unbedingt prüfen." },
    direction: { high_good: "Je höher der Wert, desto stabiler die Ressource.", low_good: "Je niedriger der Wert, desto besser. Beispiel: Zeitdruck oder Konfliktspannung." },
    trend: { steigend: "Entwickelt sich nach oben.", stabil: "Bleibt derzeit ungefähr gleich.", fallend: "Schwächt sich ab.", unklar: "Noch nicht ausreichend einschätzbar." },
    effort: { niedrig: "Mit wenig Aufwand umsetzbar.", mittel: "Benötigt Vorbereitung oder Abstimmung.", hoch: "Erfordert deutliche Ressourcen, Zeit oder Mandat." }
  };
  return data[kind]?.[value] || "Bitte fachlich prüfen und bei Bedarf überschreiben.";
}

function assumption(text, source = "Vorlage", evidence = "mittel", uncertainty = "mittel", sensitivity = "intern", sourceStatus = "abgeleitet") {
  return { id: uid(), text, source, evidence, evidenceText: explainChoice("evidence", evidence), uncertainty, uncertaintyText: explainChoice("uncertainty", uncertainty), sensitivity, sensitivityText: explainChoice("sensitivity", sensitivity), sourceStatus, sourceStatusText: explainChoice("sourceStatus", sourceStatus) };
}
function persona(name, role, stance, influence, affectedness, trust, aiLiteracy, riskSense, changeEnergy, informalRole, conflictStyle, trigger, learningNeed, communicationNeed) {
  return { id: uid(), name, role, stance, influence, influenceText: explain("influence", influence), affectedness, affectednessText: explain("affectedness", affectedness), trust, trustText: explain("trust", trust), aiLiteracy, aiLiteracyText: explain("aiLiteracy", aiLiteracy), riskSense, riskSenseText: explain("riskSense", riskSense), changeEnergy, changeEnergyText: explain("changeEnergy", changeEnergy), informalRole, conflictStyle, trigger, learningNeed, communicationNeed };
}
function resource(name, type, current, target, direction, trend, bottleneck, owner) {
  return { id: uid(), name, type, current, currentText: explain("current", current), target, targetText: explain("target", target), direction, directionText: explainChoice("direction", direction), trend, trendText: explainChoice("trend", trend), bottleneck, owner };
}
function intervention(name, timing, target, benefit, sideEffect, effort) {
  return { id: uid(), name, timing, timingText: `Intervention im Abschnitt „${timing}“ einplanen und mit Ziel sowie Nebenwirkung prüfen.`, target, benefit, sideEffect, effort, effortText: explainChoice("effort", effort) };
}
function strategy(name, description, speed, acceptance, control, innovation, risk, conditions, failureMode, decisionSignal) {
  return { id: uid(), name, description, speed, speedText: explain("speed", speed), acceptance, acceptanceText: explain("acceptance", acceptance), control, controlText: explain("control", control), innovation, innovationText: explain("innovation", innovation), risk, riskText: explain("risk", risk), conditions, failureMode, decisionSignal };
}
const commonStrategies = [
  strategy("A Governance-first", "Zuerst Regeln, Rollen, Datenklassen und Freigabewege klären.", 2, 3, 5, 3, 2, "Hohe Unsicherheit oder Schutzbedarf.", "Wird als Verhinderung gelesen.", "Wählen, wenn Sicherheit vor Tempo geht."),
  strategy("B Pilot-first", "Mit einer freiwilligen Pilotgruppe starten und aus Erfahrungen Standards ableiten.", 4, 4, 3, 5, 3, "Mindestleitplanken sind vorhanden.", "Pilot wirkt wie Schattenfreigabe oder Eliteprojekt.", "Wählen, wenn Praxislernen Priorität hat."),
  strategy("C Moderierte Klärung", "Interessen, Sorgen, Zielkonflikte und Grenzen vor Entscheidung sichtbar machen.", 3, 4, 4, 3, 2, "Sozialer Prozess ist der Engpass.", "Klärung führt nicht zu Entscheidung.", "Wählen, wenn Vertrauen und Rollenverständnis kritisch sind.")
];
function scenario(id, label, title, desc, domain, decisionQuestion, goal, assumptions, personas, resources, interventions, strategies = commonStrategies, openQuestions = [], warnings = []) {
  return { id, label, title, desc, context: { title, domain, decisionQuestion, goal, boundaries: "Keine personenbezogene Bewertung. Nur Rollen, Archetypen und anonymisierte Szenarien verwenden." }, assumptions, personas, resources, interventions, strategies: copy(strategies), openQuestions, warnings };
}

const templates = [
  scenario(
    "workshop-still", "Demo · Workshop", "Stille Gruppe im KI-Workshop", "Stille, Hierarchie und Unsicherheit als Workshop-Szenario.",
    "Workshop / KI-Literacy / Organisationsentwicklung", "Wie kann ein KI-Workshop so gestaltet werden, dass stille Teilnehmende sicher in Beteiligung kommen?", "Moderationsdesign, Beteiligung und psychologische Sicherheit prüfen.",
    [assumption("Die Gruppe ist nicht zwingend ablehnend, sondern wartet auf Signale von Leitung und Meinungsführenden."), assumption("Lange Inputphasen senken Aufmerksamkeit und verstärken passives Verhalten.")],
    [persona("Erfahrene Einrichtungsleitung", "Mittlere Führung", "vorsichtig-kritisch", 5, 4, 3, 2, 5, 2, "Meinungsführer*in", "abwartend", "Mehrarbeit, Datenschutz, Entwertung von Erfahrung", "Praxisnähe und Anerkennung", "Skepsis ausdrücklich legitimieren"), persona("KI-affine Bereichsleitung", "Projektleitung", "zustimmend", 4, 3, 4, 4, 3, 5, "Treiber*in", "lösungsorientiert", "zu viel Grundsatzdebatte", "konkrete Use Cases", "nicht als Gegenpol zur Skepsis inszenieren")],
    [resource("Aufmerksamkeit", "kognitiv", 3, 4, "high_good", "fallend", "zu lange Inputphasen", "Moderation"), resource("psychologische Sicherheit", "sozial", 2, 4, "high_good", "fallend", "Angst, sich mit Skepsis zu exponieren", "Moderation")],
    [intervention("Einzelreflexion vor Plenum", "Einstieg", "niedrigschwellige Beteiligung", "reduziert Druck", "kostet Zeit", "niedrig"), intervention("Skepsis ausdrücklich legitimieren", "früh", "Vertrauen", "kritische Stimmen werden Ressource", "Diskussion dauert länger", "niedrig")],
    commonStrategies, ["Welche Personen setzen informell den Ton?", "Welche Datenschutzfrage muss vorab beantwortet sein?"], ["Stille nicht als Zustimmung interpretieren.", "Skepsis nicht moralisieren."]
  ),
  scenario(
    "workshop-polarisiert", "Demo · Workshop", "Polarisierte Gruppe bei KI-Einführung", "Treiber- und Schutzlogik blockieren sich gegenseitig.",
    "KI-Einführung / Change / Beteiligung", "Wie kann ein KI-Einführungsprozess gestaltet werden, wenn Treiber- und Skeptikerlager entstehen?", "Gegenpositionen entpersonalisieren und eine tragfähige Entscheidungslogik entwickeln.",
    [assumption("Die Polarisierung entsteht eher aus konkurrierenden Schutz-, Tempo- und Qualitätslogiken als aus Technikfragen."), assumption("Eine schnelle Führungsentscheidung erzeugt Tempo, kann aber Vertrauen kosten.")],
    [persona("Digitale Treiberrolle", "Projektleitung", "zustimmend", 4, 4, 4, 5, 2, 5, "Treiber*in", "argumentativ", "zu viele Verbote", "Governance als Ermöglichung verstehen", "nicht als naiv markieren"), persona("Schutzorientierte Fachlichkeit", "Pädagogik", "skeptisch", 4, 5, 3, 2, 5, 3, "Frühwarnrolle", "werteorientiert", "Kontrolle, Entwertung, Datenschutz", "konkrete Grenzen", "als Schutzlogik ernst nehmen")],
    [resource("Vertrauen", "sozial", 3, 4, "high_good", "fallend", "wechselseitige Unterstellungen", "Moderation"), resource("Konfliktspannung", "sozial", 4, 2, "low_good", "steigend", "Lagerbildung", "Moderation")],
    [intervention("Steelman-Runde", "früh", "Entpersonalisierung", "jede Seite formuliert die starke faire Version der Gegenseite", "braucht reife Moderation", "mittel"), intervention("Entscheidungskriterien sichtbar machen", "Entscheidung", "Klarheit", "Tempo, Schutz, Qualität und Beteiligung werden abwägbar", "Zielkonflikte werden sichtbarer", "mittel")],
    commonStrategies, ["Welche Position ist legitime Schutzlogik?", "Welche Entscheidungskriterien sind nicht verhandelbar?"], ["Treiber nicht als naiv, Skeptiker nicht als innovationsfeindlich rahmen."]
  ),
  scenario(
    "paedagogik-heterogen", "Demo · Pädagogik", "Heterogene Lerngruppe in digitaler Unterrichtssequenz", "Differenzierung, Lernmotivation und Verstandenheit modellieren.",
    "Pädagogik / Unterrichtsentwicklung", "Wie muss eine digitale Unterrichtssequenz gestaltet werden, damit unterschiedliche Lernenden-Archetypen anschlussfähig bleiben?", "Differenzierung, Beteiligung und Transferfähigkeit prüfen.",
    [assumption("Dieselbe Methode wirkt je nach Vorwissen und Sicherheit unterschiedlich."), assumption("Stille Lernende brauchen sichere Zwischenschritte, bevor sie im Plenum sichtbar werden.")],
    [persona("Leistungsstarker Lernender", "Lerngruppe", "fordernd", 3, 3, 4, 4, 2, 4, "Treiber*in", "ungeduldig", "Langeweile durch Wiederholung", "Herausforderung und Transfer", "Erweiterungsaufgaben anbieten"), persona("Stille Lernende", "Lerngruppe", "zurückhaltend", 2, 4, 3, 3, 4, 2, "Seismograf für Klima", "vermeidend", "Bloßstellung und Fehlerangst", "sichere Übungsräume", "erst schriftlich oder zu zweit aktivieren")],
    [resource("Lernmotivation", "emotional", 3, 4, "high_good", "stabil", "Sinnfrage und Überforderung", "Lehrkraft"), resource("Verstandenheit", "kognitiv", 3, 5, "high_good", "unklar", "unterschiedliche Vorkenntnisse", "Lehrkraft")],
    [intervention("Differenzierte Aufgabenstufen", "Mitte", "Verstandenheit", "verschiedene Leistungsniveaus bleiben anschlussfähig", "höherer Vorbereitungsaufwand", "hoch"), intervention("Murmelphase vor Plenum", "früh", "psychologische Sicherheit", "stille Lernende können Gedanken vorformulieren", "verlangsamt Plenum", "niedrig")],
    [strategy("A Sicherheit-first", "Zuerst Basisverständnis und sichere Beteiligung herstellen.", 2, 4, 4, 3, 2, "Hohe Heterogenität oder Fehlerangst.", "Starke Lernende werden nicht gefordert.", "Wählen, wenn Überforderung Hauptrisiko ist."), strategy("B Challenge-first", "Mit anspruchsvollem Problem starten und differenziert unterstützen.", 4, 3, 3, 5, 4, "Aktivierung ist zentral.", "Stille oder förderbedürftige Lernende steigen aus.", "Wählen, wenn Motivation durch Herausforderung entsteht."), strategy("C Differenzierung-first", "Sequenz in Basis, Erweiterung und Transfer aufteilen.", 3, 4, 4, 4, 2, "Breites Leistungsgefälle.", "Struktur wird zu komplex.", "Wählen, wenn Anschlussfähigkeit für alle zentral ist.")],
    ["Welche Mindestkompetenz sollen alle sicher können?", "Welche Erweiterungsaufgabe fordert starke Lernende?"], ["Nicht aus Einzelverhalten auf Persönlichkeit schließen."]
  ),
  scenario(
    "angebot-bvb", "Demo · Angebotsentwicklung", "BvB-Digitalisierung als neues Angebot", "Zielgruppenbedarf, Budget, Pilotfähigkeit und Veto-Risiken.",
    "Angebotsentwicklung / Bildung / Sozialwirtschaft", "Wie kann ein digitales Angebot für die Berufsvorbereitung entwickelt werden, sodass Bedarf, Finanzierung und Umsetzbarkeit zusammenpassen?", "Bedarfsannahmen, Stakeholder-Koalitionen und Skalierungsrisiken prüfen.",
    [assumption("Das Angebot ist nur tragfähig, wenn der Zielgruppenbedarf aus Teilnehmendenperspektive belegt wird."), assumption("Budgetdruck kann fachliche Qualität und Beteiligung verkürzen.")],
    [persona("Programmleitung", "Projektleitung", "zustimmend", 5, 4, 4, 4, 3, 5, "Treiber*in", "steuernd", "langsame Abstimmung", "realistische Skalierung", "Wirkung und Grenzen balancieren"), persona("Geldgeberrolle", "Finanzierung", "prüfend", 5, 3, 3, 2, 4, 3, "Stoppsignal", "ergebnisorientiert", "unklare Wirkung", "Bedarfsnachweis und Evaluation", "Wirkungslogik und Kennzahlen")],
    [resource("Stakeholder-Vertrauen", "sozial", 3, 4, "high_good", "unklar", "unklare Wirkung und Zuständigkeit", "Projektleitung"), resource("Budgetdruck", "materiell", 4, 2, "low_good", "steigend", "Finanzierungsunsicherheit", "Programmleitung")],
    [intervention("Zielgruppeninterviews vor Konzeptfinalisierung", "vorab", "Bedarfsnachweis", "verhindert Zielgruppen-Drift", "verzögert Konzeptphase", "mittel"), intervention("Minimal-Pilot mit Evaluationsraster", "Mitte", "Pilotreife", "macht Wirkung prüfbar", "begrenzte Aussagekraft", "mittel")],
    [strategy("A Bedarfsanalyse-first", "Zuerst Zielgruppe, Bedarf und Alltagspassung prüfen.", 2, 4, 4, 3, 2, "Unklarer Bedarf.", "Analysephase wird zu lang.", "Wählen, wenn Zielgruppenpassung kritisch ist."), strategy("B Pilot-first", "Kleinen Pilot starten und Wirkung praktisch prüfen.", 4, 4, 3, 5, 3, "Mindestklarheit vorhanden.", "Scheitert ohne Evaluationsdesign.", "Wählen, wenn Lernen wichtiger ist als Vollständigkeit."), strategy("C Funding-first", "Finanzierung sichern und danach Konzept operationalisieren.", 3, 3, 4, 3, 4, "Harte Ressourcenknappheit.", "Finanzierungslogik verdrängt fachliche Passung.", "Wählen, wenn Budget zentraler Engpass ist.")],
    ["Wie wird Zielgruppenbedarf belegt?", "Welche Mindestwirkung muss der Pilot zeigen?"], ["Wirkungsversprechen nicht vor Bedarfsnachweis überziehen."]
  ),
  scenario(
    "team-storming", "Demo · Teamentwicklung", "Team in der Stormingphase", "Rollenunklarheit, informelle Macht und psychologische Sicherheit.",
    "Teamentwicklung / Führung / Konfliktklärung", "Welche Führungs- und Moderationsinterventionen helfen einem Team in der Stormingphase, ohne Konflikte zu verdecken?", "Rollenklärung, psychologische Sicherheit und konstruktive Konfliktbearbeitung vorbereiten.",
    [assumption("Der sichtbare Sachkonflikt verdeckt teilweise einen Rollen- und Anerkennungskonflikt."), assumption("Informelle Führung kann formale Rollenklärung stabilisieren oder blockieren.")],
    [persona("Teamleitung", "Mittlere Führung", "ergebnisorientiert", 5, 5, 3, 3, 4, 4, "formale Entscheidung", "steuernd", "ineffiziente Diskussionen", "Fehleranteile benennen und Rahmen halten", "nicht zu früh harmonisieren"), persona("Informelle Veteranin", "Operative Praxis", "skeptisch", 5, 4, 2, 2, 5, 2, "informelle Macht", "kritisch nachfragend", "Respektverlust und neue Regeln", "Einfluss konstruktiv nutzen", "Widerstand als Erfahrungssignal lesen")],
    [resource("psychologische Sicherheit", "sozial", 2, 4, "high_good", "fallend", "Angst vor Gesichtsverlust", "Teamleitung / Moderation"), resource("Konfliktspannung", "sozial", 5, 2, "low_good", "steigend", "ungeklärte Rollen", "Moderation")],
    [intervention("Rollenklärung mit Erwartungsabgleich", "früh", "Klarheit", "reduziert verdeckte Zuständigkeitskonflikte", "Machtfragen werden sichtbarer", "mittel"), intervention("Retrospektive ohne Schuldzuweisung", "Mitte", "psychologische Sicherheit", "macht Muster besprechbar", "braucht gutes Framing", "mittel")],
    [strategy("A Rollenklärung-first", "Zuerst Erwartungen, Verantwortlichkeiten und Schnittstellen klären.", 3, 4, 4, 3, 2, "Unklare Zuständigkeiten.", "Machtfragen bleiben verdeckt.", "Wählen, wenn Unklarheit Haupttreiber ist."), strategy("B Konfliktbearbeitung-first", "Konflikte explizit bearbeiten, bevor neue Regeln gesetzt werden.", 2, 3, 3, 3, 4, "Hohe Spannung.", "Scheitert, wenn Sicherheit fehlt.", "Wählen, wenn verdeckte Konflikte blockieren."), strategy("C Vereinbarungen-first", "Schnell gemeinsame Arbeitsregeln definieren.", 4, 3, 4, 2, 3, "Akuter Handlungsdruck.", "Regeln stabilisieren nur Oberfläche.", "Wählen, wenn sofortige Arbeitsfähigkeit nötig ist.")],
    ["Welche Rollenunklarheit erzeugt die meisten Reibungen?", "Wer kann Brückenrolle sein?"], ["Harmonie nicht mit psychologischer Sicherheit verwechseln."]
  ),
  scenario(
    "mav-governance", "Demo · Governance", "MAV-Beteiligung bei Personalführung rechtssicher gestalten", "Führung, MAV, Dokumentation, Fristen und Governance.",
    "Führung / Arbeitsrecht / MAV / Governance", "Wie können Führungskräfte rechtliche Vorgaben, MAV-Beteiligung und vertrauensvolle Personalführung zusammenbringen?", "Handlungssicherheit erhöhen, Eskalationsrisiken senken und Rollen klären.",
    [assumption("Führungskräfte benötigen sichere Orientierung zu Schwellen, Rollen und Eskalationspunkten."), assumption("Schattenakten oder informelle Dokumentation erzeugen erhebliche rechtliche und vertrauensbezogene Risiken.", "Governance-Warnung", "hoch", "niedrig", "vertraulich")],
    [persona("Strategische Führungskraft", "Mittlere Führung", "pragmatisch", 5, 5, 3, 3, 4, 4, "formale Entscheidung", "pragmatisch", "unklare Rechtslage", "Schwellen, Fristen, Gesprächslogik", "konkrete Entscheidungshilfen"), persona("MAV-Rolle", "MAV / Interessenvertretung", "schutzorientiert", 5, 4, 3, 2, 5, 3, "Frühwarnrolle", "interessenklärend", "späte Beteiligung", "Rollenklärung und transparente Kommunikation", "früh und nicht nur formal einbinden")],
    [resource("Rechtssicherheit", "governance", 3, 5, "high_good", "unklar", "uneinheitliche Anwendung", "HR / Rechtsberatung"), resource("Fristendruck", "operativ", 4, 2, "low_good", "steigend", "unklare Prozessschritte", "Prozessverantwortliche")],
    [intervention("Jour fixe Dienststellenleitung–MAV", "regelmäßig", "Vertrauen und Rollenklärung", "reduziert Überraschungen und Eskalationen", "braucht verbindliche Agenda", "mittel"), intervention("Checkliste Personalgespräch und Dokumentation", "vorab", "Prozesssicherheit", "senkt Schattenakten- und Fristrisiko", "kann formalistisch wirken", "mittel")],
    [strategy("A Schulung-first", "Führungskräfte werden durch Webinar, Fallarbeit und Checklisten handlungssicher gemacht.", 3, 4, 4, 3, 2, "Kompetenzlücken.", "Schulung wird nicht in Prozesse übersetzt.", "Wählen, wenn Wissen und Anwendung Engpass sind."), strategy("B Prozess-first", "Erst Prozess, Zuständigkeiten, Fristen und Dokumentationsstandards klären.", 2, 3, 5, 2, 2, "Uneinheitliche Praxis.", "Führung versteht Logik nicht.", "Wählen, wenn Rechts- und Dokumentationssicherheit Priorität hat."), strategy("C Vertrauens-first", "Regelmäßige Klärungsformate mit MAV etablieren, bevor Einzelfälle eskalieren.", 3, 4, 4, 3, 2, "Belastete Zusammenarbeit.", "Keine verbindliche Entscheidungslogik.", "Wählen, wenn Beziehung und Rollenverständnis Engpass sind.")],
    ["Welche Personalprozesse erzeugen die meisten Unsicherheiten?", "Wo beginnt Beteiligung früh genug?", "Wie werden Schattenakten organisatorisch verhindert?"], ["Nicht als Rechtsberatungstool missverstehen.", "MAV nicht erst bei fertiger Entscheidung informieren."]
  )
];

const initialScenario = copy(templates[0]);
const safeArray = (x) => Array.isArray(x) ? x : [];
function normalizeDraft(d) {
  return {
    context: { ...initialScenario.context, ...(d?.context || {}) },
    assumptions: safeArray(d?.assumptions).map(x => ({ ...assumption(x.text || "Import-Annahme", x.source || "Import"), ...x, id: uid() })),
    personas: safeArray(d?.personas).map(x => ({ ...persona(x.name || "Import-Rolle", x.role || "Stakeholder", x.stance || "unklar", x.influence || 3, x.affectedness || 3, x.trust || 3, x.aiLiteracy || 3, x.riskSense || 3, x.changeEnergy || 3, x.informalRole || "keine besondere informelle Rolle", x.conflictStyle || "unklar", x.trigger || "", x.learningNeed || "", x.communicationNeed || ""), ...x, id: uid() })),
    resources: safeArray(d?.resources).map(x => ({ ...resource(x.name || "Import-Ressource", x.type || "sozial", x.current || 3, x.target || 4, x.direction || "high_good", x.trend || "unklar", x.bottleneck || "", x.owner || ""), ...x, id: uid() })),
    interventions: safeArray(d?.interventions).map(x => ({ ...intervention(x.name || "Import-Intervention", x.timing || "offen", x.target || "", x.benefit || "", x.sideEffect || "", x.effort || "mittel"), ...x, id: uid() })),
    strategies: safeArray(d?.strategies).map(x => ({ ...strategy(x.name || "Import-Strategie", x.description || "", x.speed || 3, x.acceptance || 3, x.control || 3, x.innovation || 3, x.risk || 3, x.conditions || "", x.failureMode || "", x.decisionSignal || ""), ...x, id: uid() })),
    openQuestions: safeArray(d?.openQuestions),
    warnings: safeArray(d?.warnings)
  };
}
function avg(list, key) { return list.length ? list.reduce((s, x) => s + Number(x[key] || 0), 0) / list.length : 0; }
function resourceScore(r) { return (r.direction === "low_good" ? 6 - Number(r.current || 1) : Number(r.current || 1)) * 20; }
function resourceGap(r) { return r.direction === "low_good" ? Number(r.current || 1) - Number(r.target || 1) : Number(r.target || 1) - Number(r.current || 1); }
function strategyScore(s) { return Number(s.acceptance || 0) * 3 + Number(s.control || 0) * 3 + Number(s.innovation || 0) * 2 + Number(s.speed || 0) - Number(s.risk || 0) * 3; }
function compute(s) {
  const resources = safeArray(s.resources), personas = safeArray(s.personas), assumptions = safeArray(s.assumptions), interventions = safeArray(s.interventions), strategies = safeArray(s.strategies);
  const res = resources.length ? resources.reduce((a,r)=>a+resourceScore(r),0)/resources.length : 60;
  const risky = assumptions.filter(a=>a.evidence === "niedrig" || a.uncertainty === "hoch");
  const hasPrivacy = interventions.some(i=>/daten|datenschutz|grenze|faq|dokumentation/i.test(`${i.name} ${i.target}`));
  const hasParticipation = interventions.some(i=>/einwand|beteilig|freiwillig|workshop|jour fixe|rollenklärung|reflexion/i.test(`${i.name} ${i.target}`));
  const acceptance = Math.round(Math.min(100, 20 + avg(personas,"trust")*8 + avg(personas,"aiLiteracy")*3 + avg(personas,"changeEnergy")*4 + (hasParticipation?16:0) + res*.15 - risky.length*4));
  const governance = Math.round(Math.min(100, 30 + avg(personas,"riskSense")*5 + (hasPrivacy?22:0) + res*.18));
  const learning = Math.round(Math.min(100, 25 + avg(personas,"aiLiteracy")*7 + avg(personas,"changeEnergy")*5 + interventions.length*5));
  const risk = Math.round(Math.max(0, 100 - (acceptance*.35 + governance*.4 + learning*.15 + res*.1)));
  return { acceptance, governance, learning, resources: Math.round(res), risk, risky, deficits: resources.filter(r=>resourceGap(r)>0), bestStrategy: [...strategies].sort((a,b)=>strategyScore(b)-strategyScore(a))[0] };
}
function reportTitle(key){const m={executiveSummary:"Executive Summary",ausgangslage:"Ausgangslage",simulationsannahmen:"Simulationsannahmen",stakeholderanalyse:"Persona- und Stakeholderanalyse",ressourcenRisikolage:"Ressourcen- und Risikolage",phasenanalyse:"Phasenanalyse",konfliktKoalitionsmuster:"Konflikt- und Koalitionsmuster",kritischeKipppunkte:"Kritische Kipppunkte",interventionsoptionen:"Interventionsoptionen",entscheidungsmatrix:"Entscheidungsmatrix",massnahmenplan:"Maßnahmenplan",offeneFragen:"Offene Fragen",governanceHinweise:"Datenschutz-/Governance-Hinweise",grenzenDerSimulation:"Grenzen der Simulation"};return m[key]||key}
const loadSaved=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")}catch{return[]}};
const persistSaved=(x)=>localStorage.setItem(STORAGE_KEY,JSON.stringify(x));

function Card({children,className=""}){return <section className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-sm ${className}`}>{children}</section>}
function Button({children,onClick,dark=false,disabled=false}){return <button disabled={disabled} onClick={onClick} className={`${dark?"bg-slate-900 text-white":"bg-white text-slate-800 border border-slate-200"} rounded-xl px-3 py-2 text-sm font-bold disabled:opacity-50`}>{children}</button>}
function Field({label,value,onChange,area=false}){const c="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:ring-4 focus:ring-slate-100";return <label className="block"><span className="mb-1 block text-sm font-semibold text-slate-700">{label}</span>{area?<textarea className={`${c} min-h-24`} value={value||""} onChange={e=>onChange(e.target.value)}/>:<input className={c} value={value||""} onChange={e=>onChange(e.target.value)}/>}</label>}
function SelectField({label,value,onChange,options}){return <label className="block"><span className="mb-1 block text-sm font-semibold text-slate-700">{label}</span><select className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm" value={value||""} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o} value={o}>{o}</option>)}</select></label>}
function RangeText({label,value,onChange,text,kind}){return <div className="rounded-xl border bg-white p-3"><label><div className="mb-1 flex justify-between text-sm"><b>{label}</b><span>{value||3}/5</span></div><input type="range" min="1" max="5" value={value||3} onChange={e=>{const v=Number(e.target.value);onChange(v, explain(kind,v))}} className="w-full accent-slate-900"/></label><textarea className="mt-2 min-h-20 w-full rounded-xl border bg-slate-50 p-2 text-xs leading-5" value={text||""} onChange={e=>onChange(value||3,e.target.value)}/></div>}
function ChoiceText({label,value,onChange,text,kind,options}){return <div><SelectField label={label} value={value} options={options} onChange={v=>onChange(v, explainChoice(kind,v))}/><textarea className="mt-2 min-h-16 w-full rounded-xl border bg-slate-50 p-2 text-xs leading-5" value={text||""} onChange={e=>onChange(value,e.target.value)}/></div>}
function Mini({title,text}){return <div className="rounded-xl bg-white p-3"><b>{title}</b><p className="mt-2 whitespace-pre-line text-sm text-slate-600">{text||"—"}</p></div>}

function Templates({setState,setTab}){return <Card><h2 className="text-xl font-bold">Standardszenarien</h2><p className="mt-1 text-sm text-slate-600">Sechs Vorlagen zum Starten, Demonstrieren und Weiterarbeiten.</p><div className="mt-4 grid gap-4 lg:grid-cols-3">{templates.map(s=><div className="rounded-2xl border bg-slate-50 p-4" key={s.id}><div className="mb-2 inline-flex rounded-full bg-white px-3 py-1 text-xs font-bold">{s.label}</div><h3 className="font-bold">{s.title}</h3><p className="mt-2 text-sm text-slate-600">{s.desc}</p><div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-white px-2 py-1">Annahmen {s.assumptions.length}</span><span className="rounded-full bg-white px-2 py-1">Personas {s.personas.length}</span><span className="rounded-full bg-white px-2 py-1">Ressourcen {s.resources.length}</span></div><div className="mt-4"><Button dark onClick={()=>{setState(copy(s));setTab("Ausgangslage")}}>Vorlage laden</Button></div></div>)}</div></Card>}
function Dashboard({sim}){const rows=[["Akzeptanz",sim.acceptance],["Governance",sim.governance],["Ressourcen",sim.resources],["Lernfähigkeit",sim.learning],["Restrisiko",sim.risk]];return <Card><h2 className="text-xl font-bold">Dashboard</h2><div className="mt-4 grid gap-3 md:grid-cols-5">{rows.map(([k,v])=><div className="rounded-2xl border bg-slate-50 p-4" key={k}><div className="text-sm font-semibold text-slate-500">{k}</div><div className="text-3xl font-bold">{v}</div><div className="mt-2 h-2 rounded bg-slate-200"><div className="h-2 rounded bg-slate-900" style={{width:`${Math.max(0,Math.min(100,v))}%`}}/></div></div>)}</div><p className="mt-4 text-sm text-slate-600">Empfohlene Strategie: <b>{sim.bestStrategy?.name||"keine"}</b></p></Card>}
function Context({state,setState}){const u=(k,v)=>setState(s=>({...s,context:{...s.context,[k]:v}}));return <Card><h2 className="text-xl font-bold">Ausgangslage</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Titel" value={state.context.title} onChange={v=>u("title",v)}/><Field label="Domäne" value={state.context.domain} onChange={v=>u("domain",v)}/><div className="md:col-span-2"><Field area label="Entscheidungsfrage" value={state.context.decisionQuestion} onChange={v=>u("decisionQuestion",v)}/></div><Field area label="Ziel" value={state.context.goal} onChange={v=>u("goal",v)}/><Field area label="Grenzen / Nicht-Zwecke" value={state.context.boundaries} onChange={v=>u("boundaries",v)}/></div></Card>}
function Assumptions({items,setItems}){const upd=(id,patch)=>setItems(prev=>prev.map(x=>x.id===id?{...x,...patch}:x));return <Card><div className="flex justify-between"><h2 className="text-xl font-bold">Annahmen</h2><Button dark onClick={()=>setItems(prev=>[...prev,assumption("Neue Annahme","manuell","niedrig","mittel","intern","Hypothese")])}>+ Hinzufügen</Button></div><div className="mt-4 space-y-4">{items.map(a=><div className="rounded-2xl border bg-slate-50 p-4" key={a.id}><div className="grid gap-4 md:grid-cols-2"><Field area label="Annahme" value={a.text} onChange={v=>upd(a.id,{text:v})}/><Field label="Quelle" value={a.source} onChange={v=>upd(a.id,{source:v})}/><ChoiceText label="Evidenz" value={a.evidence} text={a.evidenceText} kind="evidence" options={menu.evidence} onChange={(v,t)=>upd(a.id,{evidence:v,evidenceText:t})}/><ChoiceText label="Unsicherheit" value={a.uncertainty} text={a.uncertaintyText} kind="uncertainty" options={menu.uncertainty} onChange={(v,t)=>upd(a.id,{uncertainty:v,uncertaintyText:t})}/><ChoiceText label="Sensibilität" value={a.sensitivity} text={a.sensitivityText} kind="sensitivity" options={menu.sensitivity} onChange={(v,t)=>upd(a.id,{sensitivity:v,sensitivityText:t})}/><ChoiceText label="Status" value={a.sourceStatus} text={a.sourceStatusText} kind="sourceStatus" options={menu.sourceStatus} onChange={(v,t)=>upd(a.id,{sourceStatus:v,sourceStatusText:t})}/></div><button className="mt-3 text-sm font-bold text-rose-700" onClick={()=>setItems(prev=>prev.filter(x=>x.id!==a.id))}>löschen</button></div>)}</div></Card>}
function Personas({items,setItems}){const upd=(id,patch)=>setItems(prev=>prev.map(x=>x.id===id?{...x,...patch}:x));return <Card><div className="flex justify-between"><h2 className="text-xl font-bold">Personas</h2><Button dark onClick={()=>setItems(prev=>[...prev,persona("Neue Rolle","Stakeholder","unklar",3,3,3,3,3,3,"keine besondere informelle Rolle","unklar","","","")])}>+ Hinzufügen</Button></div><div className="mt-4 space-y-4">{items.map(p=><div className="rounded-2xl border bg-slate-50 p-4" key={p.id}><div className="grid gap-4 md:grid-cols-2"><Field label="Name" value={p.name} onChange={v=>upd(p.id,{name:v})}/><SelectField label="Rolle" value={p.role} onChange={v=>upd(p.id,{role:v})} options={menu.role}/><SelectField label="Haltung" value={p.stance} onChange={v=>upd(p.id,{stance:v})} options={menu.stance}/><SelectField label="Informelle Rolle" value={p.informalRole} onChange={v=>upd(p.id,{informalRole:v})} options={menu.informalRole}/><SelectField label="Konfliktstil" value={p.conflictStyle} onChange={v=>upd(p.id,{conflictStyle:v})} options={menu.conflictStyle}/><Field label="Trigger" value={p.trigger} onChange={v=>upd(p.id,{trigger:v})}/>{[["influence","Einfluss","influenceText"],["affectedness","Betroffenheit","affectednessText"],["trust","Vertrauen","trustText"],["aiLiteracy","KI-Kompetenz","aiLiteracyText"],["riskSense","Risikoempfinden","riskSenseText"],["changeEnergy","Veränderungsenergie","changeEnergyText"]].map(([k,l,tk])=><RangeText key={k} label={l} value={p[k]} text={p[tk]} kind={k} onChange={(v,t)=>upd(p.id,{[k]:v,[tk]:t})}/>) }<Field area label="Lernbedarf" value={p.learningNeed} onChange={v=>upd(p.id,{learningNeed:v})}/><Field area label="Kommunikationsbedarf" value={p.communicationNeed} onChange={v=>upd(p.id,{communicationNeed:v})}/></div><button className="mt-3 text-sm font-bold text-rose-700" onClick={()=>setItems(prev=>prev.filter(x=>x.id!==p.id))}>löschen</button></div>)}</div></Card>}
function Resources({items,setItems}){const upd=(id,patch)=>setItems(prev=>prev.map(x=>x.id===id?{...x,...patch}:x));return <Card><div className="flex justify-between"><h2 className="text-xl font-bold">Ressourcen</h2><Button dark onClick={()=>setItems(prev=>[...prev,resource("Neue Ressource","sozial",3,4,"high_good","stabil","","")])}>+ Hinzufügen</Button></div><div className="mt-4 space-y-4">{items.map(r=><div className="rounded-2xl border bg-slate-50 p-4" key={r.id}><div className="grid gap-4 md:grid-cols-2"><Field label="Ressource" value={r.name} onChange={v=>upd(r.id,{name:v})}/><SelectField label="Typ" value={r.type} onChange={v=>upd(r.id,{type:v})} options={menu.resourceType}/><ChoiceText label="Logik" value={r.direction} text={r.directionText} kind="direction" options={menu.direction} onChange={(v,t)=>upd(r.id,{direction:v,directionText:t})}/><ChoiceText label="Trend" value={r.trend} text={r.trendText} kind="trend" options={menu.trend} onChange={(v,t)=>upd(r.id,{trend:v,trendText:t})}/><RangeText label="Aktueller Wert" value={r.current} text={r.currentText} kind="current" onChange={(v,t)=>upd(r.id,{current:v,currentText:t})}/><RangeText label="Zielwert" value={r.target} text={r.targetText} kind="target" onChange={(v,t)=>upd(r.id,{target:v,targetText:t})}/><Field area label="Engpass / Kipprisiko" value={r.bottleneck} onChange={v=>upd(r.id,{bottleneck:v})}/><Field area label="Beobachten / Verantwortlich" value={r.owner} onChange={v=>upd(r.id,{owner:v})}/></div><button className="mt-3 text-sm font-bold text-rose-700" onClick={()=>setItems(prev=>prev.filter(x=>x.id!==r.id))}>löschen</button></div>)}</div></Card>}
function Interventions({items,setItems}){const upd=(id,patch)=>setItems(prev=>prev.map(x=>x.id===id?{...x,...patch}:x));return <Card><div className="flex justify-between"><h2 className="text-xl font-bold">Interventionen</h2><Button dark onClick={()=>setItems(prev=>[...prev,intervention("Neue Intervention","offen","","","","mittel")])}>+ Hinzufügen</Button></div><div className="mt-4 space-y-4">{items.map(i=><div className="rounded-2xl border bg-slate-50 p-4" key={i.id}><div className="grid gap-4 md:grid-cols-2"><Field label="Name" value={i.name} onChange={v=>upd(i.id,{name:v})}/><SelectField label="Zeitpunkt" value={i.timing} onChange={v=>upd(i.id,{timing:v,timingText:`Intervention im Abschnitt „${v}“ einplanen und mit Ziel sowie Nebenwirkung prüfen.`})} options={menu.timing}/><Field area label="Zeitpunkt-Begründung" value={i.timingText} onChange={v=>upd(i.id,{timingText:v})}/><Field label="Ziel" value={i.target} onChange={v=>upd(i.id,{target:v})}/><Field area label="Nutzen" value={i.benefit} onChange={v=>upd(i.id,{benefit:v})}/><Field area label="Nebenwirkung" value={i.sideEffect} onChange={v=>upd(i.id,{sideEffect:v})}/><ChoiceText label="Aufwand" value={i.effort} text={i.effortText} kind="effort" options={menu.effort} onChange={(v,t)=>upd(i.id,{effort:v,effortText:t})}/></div><button className="mt-3 text-sm font-bold text-rose-700" onClick={()=>setItems(prev=>prev.filter(x=>x.id!==i.id))}>löschen</button></div>)}</div></Card>}
function Strategies({items,setItems}){const upd=(id,patch)=>setItems(prev=>prev.map(x=>x.id===id?{...x,...patch}:x));return <Card><h2 className="text-xl font-bold">Strategien</h2><p className="text-sm text-slate-600">Slider ändern automatisch die Begründungstexte; alle Subtexte bleiben überschreibbar.</p><div className="mt-4 space-y-4">{items.map(st=><div className="rounded-2xl border bg-slate-50 p-4" key={st.id}><Field label="Name" value={st.name} onChange={v=>upd(st.id,{name:v})}/><div className="mt-3"><Field area label="Grundidee" value={st.description} onChange={v=>upd(st.id,{description:v})}/></div><div className="mt-4 grid gap-3 lg:grid-cols-5">{[["speed","Tempo","speedText"],["acceptance","Akzeptanz","acceptanceText"],["control","Kontrolle","controlText"],["innovation","Innovation","innovationText"],["risk","Risiko","riskText"]].map(([k,l,tk])=><RangeText key={k} label={l} value={st[k]} text={st[tk]} kind={k} onChange={(v,t)=>upd(st.id,{[k]:v,[tk]:t})}/>)}</div><div className="mt-3 grid gap-3 md:grid-cols-3"><Field area label="Bedingungen" value={st.conditions} onChange={v=>upd(st.id,{conditions:v})}/><Field area label="Scheiternsmodus" value={st.failureMode} onChange={v=>upd(st.id,{failureMode:v})}/><Field area label="Entscheidungssignal" value={st.decisionSignal} onChange={v=>upd(st.id,{decisionSignal:v})}/></div></div>)}</div></Card>}
function ImportPanel({setState,setTab}){const [text,setText]=useState("");const [draft,setDraft]=useState(null);const [documentType,setDocumentType]=useState("Konzept");const [analysisMode,setAnalysisMode]=useState("beratend");const [status,setStatus]=useState("idle");const [err,setErr]=useState("");async function runImport(){setStatus("loading");setErr("");try{const res=await fetch("/api/import-scenario",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,documentType,analysisMode})});if(!res.ok)throw new Error(await res.text());setDraft(normalizeDraft(await res.json()));setStatus("done")}catch(e){setErr(String(e.message||e));setStatus("error")}}async function file(e){const f=e.target.files?.[0];if(!f)return;if(f.size>1024*1024){setErr("Datei größer als 1 MB.");return}if(!f.name.toLowerCase().match(/\.(txt|md|json)$/)&&!f.type.startsWith("text/")){setErr("Upload Light unterstützt aktuell TXT, MD, JSON und reine Textdateien.");return}setText(await f.text())}return <Card><h2 className="text-xl font-bold">Import Light</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><SelectField label="Dokumenttyp" value={documentType} onChange={setDocumentType} options={menu.documentType}/><SelectField label="Analysemodus" value={analysisMode} onChange={setAnalysisMode} options={menu.analysisMode}/><label><span className="mb-1 block text-sm font-semibold">Datei hochladen</span><input type="file" accept=".txt,.md,.json,text/*" onChange={file} className="w-full rounded-xl border bg-white p-2 text-sm"/></label></div><textarea className="mt-4 min-h-64 w-full rounded-2xl border p-4 text-sm" value={text} onChange={e=>setText(e.target.value)} placeholder="Konzepttext einfügen oder Textdatei hochladen."/><div className="mt-3 flex gap-2"><Button dark disabled={status==="loading"||text.trim().length<80} onClick={runImport}>{status==="loading"?"Analysiere ...":"Szenarioentwurf erzeugen"}</Button>{draft&&<Button onClick={()=>setDraft(null)}>Entwurf verwerfen</Button>}</div>{err&&<div className="mt-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{err}</div>}{draft&&<div className="mt-5 rounded-2xl border bg-slate-50 p-4"><h3 className="font-bold">Review vor Übernahme</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><Mini title="Ausgangslage" text={`${draft.context.title}\n${draft.context.decisionQuestion}`}/><Mini title="Offene Fragen" text={draft.openQuestions.join("\n")}/></div><div className="mt-4"><Button dark onClick={()=>{setState(draft);setDraft(null);setTab("Ausgangslage")}}>Entwurf übernehmen</Button></div></div>}</Card>}
function Report({state,sim}){const [status,setStatus]=useState("local"),[gpt,setGpt]=useState(null);async function run(){setStatus("loading");try{const r=await fetch("/api/simulate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({state})});if(!r.ok)throw new Error(await r.text());setGpt(await r.json());setStatus("done")}catch{setStatus("error")}}const sections=gpt?Object.entries(gpt).map(([k,v])=>[reportTitle(k),v]):[["Executive Summary",`${state.context.title}\nAkzeptanz ${sim.acceptance}, Governance ${sim.governance}, Ressourcen ${sim.resources}, Restrisiko ${sim.risk}.`],["Ressourcenengpässe",sim.deficits.map(r=>`${r.name}: ${r.bottleneck}`).join("\n")||"keine"],["Riskante Annahmen",sim.risky.map(a=>a.text).join("\n")||"keine"],["Strategie",sim.bestStrategy?.name||"keine"]];return <Card><div className="flex justify-between"><h2 className="text-xl font-bold">Report</h2><div className="flex gap-2"><Button onClick={run}>GPT-Report</Button><Button dark onClick={()=>navigator.clipboard?.writeText(sections.map(([a,b])=>`${a}\n${b}`).join("\n\n"))}>Kopieren</Button></div></div><p className="mt-2 text-sm text-slate-500">Status: {status}</p><div className="mt-4 grid gap-3 md:grid-cols-2">{sections.map(([k,v])=><div className="rounded-2xl border bg-slate-50 p-4" key={k}><b>{k}</b><p className="mt-2 whitespace-pre-line text-sm">{String(v)}</p></div>)}</div></Card>}
function Storage({state,setState,saved,setSaved}){const [name,setName]=useState(state.context.title);function save(){const item={id:uid(),name:name||state.context.title,date:new Date().toISOString(),state};const next=[item,...saved];setSaved(next);persistSaved(next)}function load(item){setState(item.state)}function duplicate(item){const next=[{id:uid(),name:item.name+" Kopie",date:new Date().toISOString(),state:item.state},...saved];setSaved(next);persistSaved(next)}function del(id){const next=saved.filter(x=>x.id!==id);setSaved(next);persistSaved(next)}return <Card><h2 className="text-xl font-bold">Speichern und Laden</h2><div className="mt-4 flex gap-2"><input className="flex-1 rounded-xl border p-2" value={name} onChange={e=>setName(e.target.value)}/><Button dark onClick={save}>Aktuelles Szenario speichern</Button></div><div className="mt-4 space-y-3">{saved.map(item=><div className="rounded-2xl border bg-slate-50 p-4" key={item.id}><b>{item.name}</b><div className="text-xs text-slate-500">{new Date(item.date).toLocaleString()}</div><div className="mt-2 flex gap-2"><Button onClick={()=>load(item)}>Laden</Button><Button onClick={()=>duplicate(item)}>Duplizieren</Button><Button onClick={()=>del(item.id)}>Löschen</Button></div></div>)}</div></Card>}
function Compare({saved}){const [a,setA]=useState(""),[b,setB]=useState("");const A=saved.find(x=>x.id===a)?.state,B=saved.find(x=>x.id===b)?.state;const ca=A?compute(A):null,cb=B?compute(B):null;return <Card><h2 className="text-xl font-bold">Vergleich</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><select className="rounded-xl border p-2" value={a} onChange={e=>setA(e.target.value)}><option value="">Simulation A wählen</option>{saved.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select className="rounded-xl border p-2" value={b} onChange={e=>setB(e.target.value)}><option value="">Simulation B wählen</option>{saved.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>{ca&&cb&&<table className="mt-4 w-full text-sm"><thead><tr><th className="p-2 text-left">Kriterium</th><th>A</th><th>B</th><th>Delta</th></tr></thead><tbody>{[["Akzeptanz","acceptance"],["Governance","governance"],["Ressourcen","resources"],["Lernfähigkeit","learning"],["Restrisiko","risk"]].map(([l,k])=><tr className="border-t" key={k}><td className="p-2 font-semibold">{l}</td><td>{ca[k]}</td><td>{cb[k]}</td><td>{cb[k]-ca[k]}</td></tr>)}</tbody></table>}</Card>}

const tabs=["Dashboard","Vorlagen","Import","Ausgangslage","Annahmen","Personas","Ressourcen","Interventionen","Strategien","Report","Speicher","Vergleich"];
export default function App(){const [state,setState]=useState(initialScenario);const [tab,setTab]=useState("Vorlagen");const [saved,setSaved]=useState([]);useEffect(()=>setSaved(loadSaved()),[]);const sim=useMemo(()=>compute(state),[state]);const set=(key,val)=>setState(s=>({...s,[key]: typeof val === "function" ? val(s[key] || []) : val}));const views={Dashboard:<Dashboard sim={sim}/>,Vorlagen:<Templates setState={setState} setTab={setTab}/>,Import:<ImportPanel setState={setState} setTab={setTab}/>,Ausgangslage:<Context state={state} setState={setState}/>,Annahmen:<Assumptions items={state.assumptions} setItems={v=>set("assumptions",v)}/>,Personas:<Personas items={state.personas} setItems={v=>set("personas",v)}/>,Ressourcen:<Resources items={state.resources} setItems={v=>set("resources",v)}/>,Interventionen:<Interventions items={state.interventions} setItems={v=>set("interventions",v)}/>,Strategien:<Strategies items={state.strategies} setItems={v=>set("strategies",v)}/>,Report:<Report state={state} sim={sim}/>,Speicher:<Storage state={state} setState={setState} saved={saved} setSaved={setSaved}/>,Vergleich:<Compare saved={saved}/>};return <main className="min-h-screen bg-slate-100 p-4 text-slate-900 md:p-8"><div className="mx-auto max-w-7xl space-y-5"><header className="rounded-3xl bg-slate-950 p-8 text-white"><div className="mb-3 inline-flex rounded-full border border-white/20 px-3 py-1 text-sm">KI-Kernel GPT 0.7</div><h1 className="text-4xl font-bold">Geführte Szenariomodellierung</h1><p className="mt-3 max-w-3xl text-slate-300">Sechs Standardszenarien, geführte Menüs, Slider mit überschreibbaren Subtexten, Import, Report, Speicher und Vergleich.</p><div className="mt-5 flex gap-3"><Button onClick={()=>{setState(copy(templates[0]));setTab("Ausgangslage")}}>Demo neu laden</Button><a className="rounded-xl border border-white/20 bg-white/10 px-3 py-2 text-sm font-bold" href="/hilfe.html" target="_blank" rel="noreferrer">Hilfe öffnen</a></div></header><nav className="sticky top-2 z-10 overflow-x-auto rounded-2xl border bg-white/90 p-2 shadow-sm backdrop-blur"><div className="flex min-w-max gap-2">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl px-3 py-2 text-sm font-bold ${tab===t?"bg-slate-900 text-white":"text-slate-600 hover:bg-slate-100"}`}>{t}</button>)}<a href="/hilfe.html" target="_blank" rel="noreferrer" className="rounded-xl px-3 py-2 text-sm font-bold text-slate-600 hover:bg-slate-100">Hilfe</a></div></nav>{views[tab]}<footer className="rounded-2xl border bg-white p-4 text-xs text-slate-500">Alle automatisch erzeugten Subtexte sind überschreibbar. Speicherung erfolgt lokal im Browser. Keine echten personenbezogenen Profile verwenden.</footer></div></main>}
